### ISSUE TITLE
pokemon hearthgold españish black screen even whit ap patch

### ISSUE THREAD

**Issue by Ryper-maximoft** [DS-Homebrew/nds-bootstrap#1204] opened 2021-07-07 19:14 UTC
**Your console:** nintendo 3ds
**Launch Method:** sd card using twilight menu latest version 21-0-3
**Version used:** latest version 0.43.2
**Game tested/used/applicable:** not sure on this one but already tested the game before and in worked in previus version whit and whiout ap patch

**Expected Behavior:** works
**Actual Behavior:** black screen afther you load the game data even if it is is a previus save or you start new data

### Steps to reproduce

i tested afther updating nds bootstrap and dont work so i try a clean installs and have the same result as well

### Other notes

im using an original game is not a romhack

**Comment by RocketRobz** [comment] 2021-07-07 19:44
Duplicate of #1182

**Closed by RocketRobz** 2021-07-07 19:44 UTC
