### ISSUE TITLE
Data Abort Mario & Luigi Bowser's Inside Story

### ISSUE THREAD

**Issue by rochuj** [DS-Homebrew/nds-bootstrap#1725] opened 2024-08-20 13:51 UTC
### Game Console(s) used

- [X] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD card with TwilightMenu

### Version used

nds-bootstrap v1.5.5

### Game tested/used/applicable

Mario & Luigi Bowser's Inside Story (both EU and USA versions)

### Expected Behavior

Game should open save file and play

### Actual Behavior

Game gives me red screen 
![obraz_2024-08-20_154939060](https://github.com/user-attachments/assets/547663fa-fe17-4acd-81c1-0fa66e0087ee)

### Steps to reproduce

-

### nds-bootstrap.ini

-

### Logs

-

### Other notes

So my game crashed with red screen like about 30 minutes after I started my playthrough. Then when i tried to load latest save the same red screen with caption "DATA ABORT" happened. I tried to update TwilightMenu and install clear roms but nothing seems to work.

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment] 2024-09-03 01:58
Duplicate of #1490
according to the information on the error screen.

**Comment by RocketRobz** [comment] 2024-09-03 01:58
Duplicate of #1490

**Closed by RocketRobz** 2024-09-03 01:58 UTC
