### ISSUE TITLE
Pokémon HeartGold (U) (Randomized) (IPKE) isn't detected as AP patched, crashes randomly

### ISSUE THREAD

**Issue by barroer** [DS-Homebrew/nds-bootstrap#1211] opened 2021-07-17 00:14 UTC
**Your console:** New3DS XL
**Launch Method:** Via SD Card through TwilightMenu++
**Version used:** Stable TwilightMenu++ v.21.1.1, with the built-in nds-boostrap v.0.44.2
**Game tested/used/applicable:** Pokémon HeartGold (U) (Randomized) (IPKE)

**Expected Behavior:** The game should boot normally and without giving an Anti-Piracy Warning nor having random black screen crashes
**Actual Behavior:** The game prompts an Anti-Piracy Warning upon trying to boot it, something that shouldn't happen as TwilightMenu++ has a built-in AP patch for Pokémon HeartGold (U) (Randomized) (IPKE). When I play it, it randomly crashes giving a black screen.

### Steps to reproduce

Get your Randomized HeartGold IPKE ROM and try to boot it using the mentioned nds-bootstrap version, and play for a little while to experience the black screen crashes. They seem to happen randomly with no specific trigger, but they have happened twice in 15 minutes, when entering a house and leaving a battle. I am sorry, but I don't know how nor where to get the nds-boostrap.ini, I will upload it if I find it.

### Other notes

I have randomized the ROM myself, I don't know if that has anything to do with the AP patch not working for it, but the ROM version is the one stated above. Now that I think about it, I am not sure if this is an issue related to nds-bootstrap or Twilight Menu++ as the issue might be from the latter not properly detecing the built-in AP patch for Pokémon HeartGold (U) (Randomized) (IPKE). If I need to do anything else to give further information about the issue, please tell me so and I will be glad to provide said info.

**Comment by katykat5099** [comment] 2021-09-09 22:54
I can confirm this as I am also having this issue on multiple devices.

**Comment by Allinxter** [comment] 2021-09-09 23:11
IIRC you have to AP patch the game yourself and then randomize it, as randomizing changes the games ID and doesn't apply the existent patch.

**Comment by katykat5099** [comment] 2021-09-09 23:12
> IIRC you have to AP patch the game yourself and then randomize it, as randomizing changes the games ID and thus TWiLight doesn't make nds-bootstrap apply the existent patch.

Figured as much, Thanks. <3

**Comment by Kaisaan** [comment] 2022-02-19 07:33
Since this only happens with randomized ROMs, manually AP-patching along with using the latest version of TWiLight Menu++ nds-bootstrap should fix any crashes. Closing.

**Closed by Kaisaan** 2022-02-19 07:33 UTC
