### ISSUE TITLE
Pokémon B2W2 Freezes on DSi mode

### ISSUE THREAD

**Issue by EmperorOfTigers** [DS-Homebrew/nds-bootstrap#1127] opened 2021-04-21 15:27 UTC
**Your console:** DSi Xl
**Launch Method:** Unlaunch 2.0 with TwiLight++ v20.0.1 
**Version used:** Release v0.39.0
**Game tested/used/applicable:** Pokémon Black 2, Pokémon White 2 (Both USA/ Europe)

**Expected Behavior:** Game should load and once loading save or starting new game and picking your name and gender the game should take you to the season screen and then the overworld
**Actual Behavior:** When loading the save or choosing your name on a new save the game freezes just before the season would show

### Steps to reproduce
1. Make sure Pokémon Black 2/White 2 is set to run in DSi mode
2. Run the game
3. Select your save data or start a new game and go through the introduction
4. The game will freeze just before the season should show up on screen.

### Other notes
Games both still work correctly in DS mode.

**Comment by SNBeast** [comment] 2021-04-21 15:55
This issue better fits the TWiLight Menu++ repo, since as far as we can tell this issue is caused by previously unknown DSi mode anti-piracy, and AP patching is handled by nds-bootstrap frontends like TM++. Thank you for reporting, though!

**Comment by EmperorOfTigers** [comment] 2021-04-21 16:05
Ah my bad. I wasn't really aware of exactly what was causing it in all honesty. Thank you for your reply and understanding.

**Comment by Kaisaan** [comment] 2021-04-21 22:56
Going to close this now since issue [#1422](https://github.com/DS-Homebrew/TWiLightMenu/issues/1422) on the github for TWiLight Menu++ covers this now.

**Closed by Kaisaan** 2021-04-21 22:56 UTC
