### ISSUE TITLE
Weird sound when nds game is saving in Ace3DS+

### ISSUE THREAD

**Issue by mrcmrc123** [DS-Homebrew/nds-bootstrap#1517] opened 2023-01-22 19:58 UTC
I am on a DS lite and using an SD card for Twilight Menu, latest update. This isn't really much of an issue because the the game itself works fine, but the sound catches me off guard sometimes. But whenever the game is starting, updating the save file or making a save file, I hear a very loud noise. It sounds a bit like static. 
P.S. This happens for all NDS games but not gb or gba. 

https://user-images.githubusercontent.com/123327772/213937492-b9ebeb6b-d6d1-43a9-833e-410faeb4fa10.mov

**Comment by RocketRobz** [comment] 2023-01-22 21:05
I'm not getting this issue on my side, and it should've already been fixed some versions ago.
Please verify that you're on the latest by checking both TWLMenu++ Settings and the GitHub pages for both TWLMenu++ and nds-bootstrap.
If the issue persists, which flashcard are you using?

**Comment by mrcmrc123** [comment] 2023-01-23 17:37
I am on the latest, I checked. It probably is a problem with the flashcard, cause i got a cheap one from amazon that runs Ace 3DS + . If it helps I have a 32 gb micro sd and here is the amazon listing for the flashcard. Right now it seems like a flash card problem to me. https://www.amazon.com/Card%EF%BC%8C3DS-Flashcard-Adapter-Support-Nintendo-DS/dp/B098T6VMYQ

**Comment by bulzipke** [comment] 2023-02-15 19:04
I have exactly the same problem.
Only occurs on ACE3DS+.

The problem did not occur with R4i-SDHC (r4isdhc.com) and R4i Gold 3DS (r4ids.cn).
Above tested by the same SD card and nds-bootstrap v0.70.0.

**Comment by lifehackerhansol** [comment] 2023-04-10 04:03
I am not seeing this issue on my Ace3DS+ with v0.71.0. Has anyone else reproduced it since the last comment?

**Comment by bulzipke** [comment] 2023-04-10 04:40
My ACE3DS+ is broken and hard to check..
@mrcmrc123 can you check it?

**Comment by CheezyFriez12** [comment] 2023-07-27 03:04
I have the same issue when loading games like mario kart ds or kirby squeak squad. Mine is an ace3dsx but the only difference between ace3ds+ and ace3dsx is the 3ds modding features.

**Comment by RocketRobz** [comment] 2023-08-05 07:33
This reportedly has been fixed in later commits. Can anyone test with latest nightly?

**Comment by RocketRobz** [comment] 2024-09-03 01:56
Closing, as this issue has not been reported lately.

**Closed by RocketRobz** 2024-09-03 01:56 UTC
Labels: Bug, Retail, Cannot reproduce, B4DS
