### ISSUE TITLE
WarioWare D.I.Y cannot fully save

### ISSUE THREAD

**Issue by UDXS** [DS-Homebrew/nds-bootstrap#306] opened 2018-07-12 09:25 UTC
I've tested this in both release and nightly. The game runs totally fine but, after restarting it, it doesn't save any progress and reverts to a factory state.

**Comment by dubbz82** [comment] 2018-07-12 14:12
This game does work with a donor cart.  I know the devs are aware of this already too but good to have it documented here.

**Comment by UDXS** [comment] 2018-07-12 16:49
How do I use a donor cart with DSi Menu++?

**Comment by OmeletHopper** [comment] 2018-07-12 19:21
Simply have a cart inserted in your console that has a matching SDK with the game you are launching.

**Comment by Robz8** [comment] 2018-07-12 19:25
It's not the SDK that has to match. It's the save chip.
To clear things up, the SDK is what the DS game is compiled with, and the save chips are what stores the game save. There's two types of save chips, EEPROM and FLASH.
WW DIY however, uses a NAND save chip, and is the only game to do so.

**Comment by UDXS** [comment] 2018-07-12 19:52
Interesting. Hopefully, this will get fixed.

Thanks for the help.

**Comment by dubbz82** [comment] 2018-07-12 23:07
It will require what boils down to game specific code for it to work, so it's likely not very high priority at the moment.

**Comment by ahezard** [comment] 2019-01-16 22:02
From GBATEK :
Warioware D.I.Y. (uses a single NAND FLASH chip for both 'ROM' and 'SAVE')

**Comment by ahezard** [comment] 2019-01-16 22:03
Most probably, since there are only one chip on the card, save access are done from the ARM9. This have to be confirmed but it makes things harder to implement. 
This is the only game that does that so a very specific code is probably present and needs to be reverse engineered. Then specific patches have to be developed.

**Comment by ahezard** [comment] 2019-03-12 22:34
Wood contains a dedicated specific code/patch for WarioWare D.I.Y (nand saving)
https://github.com/ahezard/woodrpg_forwarder/blob/e0280c91b21e28443c23f98a171012ef8a301b0c/akloader/arm9/source/patches_sd.cpp
Something like that have to be done also in nds-bootstrap
Jam with the Band seems to uses nand for saves also

**Comment by ahezard** [comment] 2019-05-18 06:55
Seems to work now

**Comment by MaymonAdir** [comment] 2019-09-02 15:18
I have the same issue Dartz150

**Comment by VictorMX2307** [comment] 2020-02-29 20:52
same for me

**Comment by Dartz150** [comment] 2020-03-05 15:58
Found this on DeSmuME src: 

https://github.com/masterfeizz/DeSmuME/blob/master/src/addons/slot1_retail_nand.cpp

it explains a bit how NAND save type works.

**Comment by VictorMX2307** [comment] 2020-03-06 00:59
i just want to make diy minigames pls fix 😭

**Comment by VictorMX2307** [comment] 2020-03-15 15:35
hope its fixed on this year...

**Comment by BlueZ-DJ** [comment] 2020-04-08 20:44
The reopening of this thread is the most hopeful thing I've ever seen

**Comment by VictorMX2307** [comment] 2020-04-10 21:10
now the game wont open it says an error as ocurred

**Comment by RocketRobz** [comment] 2020-04-10 21:10
That will be fixed in the next version.

**Comment by jeffyjeffy1023** [comment] 2020-04-15 04:05
Aw man... But when will the next version drop?

**Comment by rool36** [comment] 2020-04-21 14:08
I'm new to cfw and it's the first game it got lol. Wanted to know if the new version is out? And how to get it? Thanks.

**Comment by RocketRobz** [comment] 2020-04-21 15:08
@jeffyjeffy1023 @rool36 
The new version is out. Download it from the release page, or update TWiLight Menu++.

**Comment by Nintendo-png** [comment] 2020-04-23 23:31
Now WarioWare DIY is stuck at Creating save file.

**Comment by RocketRobz** [comment] 2020-04-23 23:32
Just close the lid and reopen.

**Comment by rool36** [comment] 2020-04-23 23:34
Sorry in advance but what is a Lid? Explain what that is, please, and how to you close it?

**Comment by RocketRobz** [comment] 2020-04-23 23:36
You know, the top lid of the console? Know how to put the console in sleep mode?

**Comment by rool36** [comment] 2020-04-23 23:38
Ah I get it now that makes sense. Thanks

**Comment by Nintendo-png** [comment] 2020-04-23 23:42
It saves!

**Comment by rool36** [comment] 2020-04-23 23:53
Nice!

**Comment by Nintendo-png** [comment] 2020-04-24 01:02
This is unfortunate. Microgames won't save this time.

**Comment by BlueZ-DJ** [comment] 2020-04-24 01:07
> This is unfortunate. Microgames won't save this time.

Yeah that's the reason this thread exists, right now only progress saves, but not your creations

**Comment by rool36** [comment] 2020-04-24 01:20
Man I want the games to save. But they use band files. Best we can do is wait and support the coders

**Comment by jeffyjeffy1023** [comment] 2020-04-29 00:33
Alright, so that audio issue with the Game Makermatic that I told rob is still here, but it's less intense. Closing/Reopening the lid fixes it still.

**Comment by TheGaboefects** [comment] 2020-04-29 02:23
I hope you guys manage to fix the issue, i have tons of minigames in a old save file that i can´t access.
PD: The save file can be read just fine using an R4, can someone explain me why is different?

**Comment by Nintendo-png** [comment] 2020-04-29 02:32
Probably because the R4 uses a game slot and has more support?

**Comment by RocketRobz** [comment] 2020-04-29 02:34
@Nintendo-png No. It's because the firmware patches more functions that nds-bootstrap currently doesn't.

**Comment by Nintendo-png** [comment] 2020-04-29 02:36
Maybe you could import the patches from the R4 firmware. Is it open source?

**Comment by NightYoshi370** [comment] 2020-04-29 03:01
kernel*
Also, the R4 kernel is not open source. The Wood R4 kernel is, but the code is spaghetti according to ahezard.

**Comment by BlueZ-DJ** [comment] 2020-05-03 16:42
> I hope you guys manage to fix the issue, i have tons of minigames in a old save file that i can´t access.
> PD: The save file can be read just fine using an R4, can someone explain me why is different?

I don't know if this helps but similarly, the DeSmuMe emulator also saves microgames fine (without needing save states)

**Comment by Nintendo-png** [comment] 2020-05-03 17:25
Drastic also reads nand saves fine.

**Comment by VictorMX2307** [comment] 2020-05-03 18:03
i completed the game just for waiting it fixes lol

**Comment by VictorMX2307** [comment] 2020-07-31 15:58
hey i founded a way out to save games, music and comics is on the makermatic itself but we only have 2 spaces to save...

**Comment by jeffyjeffy1023** [comment] 2020-07-31 16:10
What, in those online boxes using alternate WFC?

On Jul 31, 2020 11:58 AM, MixedVictor <notifications@github.com> wrote:

hey i founded a way out to save games, music and comics is on the makermatic itself but we only have 2 spaces to save...

**Comment by VictorMX2307** [comment] 2020-07-31 16:16
> What, in those online boxes using alternate WFC?>.

uhhh its on makermatic itself not the wfc. (You create the game and let it saved right?)

**Comment by TheGaboefects** [comment] 2020-07-31 16:53
How???
Why is it limited to 2 spaces?

Enviado desde mi iPhone

El 31 jul. 2020, a la(s) 11:58 a. m., MixedVictor <notifications@github.com<mailto:notifications@github.com>> escribió:


hey i founded a way out to save games, music and comics is on the makermatic itself but we only have 2 spaces to save...

**Comment by VictorMX2307** [comment] 2020-07-31 17:58
> How??? Why is it limited to 2 spaces?
I dont know maybe the ds storage is too small then it uses nand to store all the games (i know nothing about ds storage and nand just talking)

**Comment by jeffyjeffy1023** [comment] 2020-07-31 18:01
The DS and DS Lite only have enough NAND on board for the firmware + user settings. Plus, cartridge games (if played on a real cart or flashcart) save to the cartridge itself you chimbo

On Jul 31, 2020 1:59 PM, MixedVictor <notifications@github.com> wrote:

How??? Why is it limited to 2 spaces?<
I dont know maybe the ds storage is too small then it uses nand to store all the games (i know nothing about ds storage and nand just talking)

**Comment by VictorMX2307** [comment] 2020-07-31 18:02
@jeffyjeffy1023 Yeah you're right...

**Comment by jeffyjeffy1023** [comment] 2020-07-31 18:13
It's alright. Not everyone knows everything.

On Jul 31, 2020 2:02 PM, MixedVictor <notifications@github.com> wrote:

@jeffyjeffy1023<https://github.com/jeffyjeffy1023> Yeah you're right...

**Comment by Dartz150** [comment] 2020-07-31 19:00
Ok, let me get this clear. You are saying that the game now actually saves, but it onlyu can do it in two slots? I'm a bit confused with this conversation because of the mail respones mess.

**Comment by VictorMX2307** [comment] 2020-07-31 19:01
> Ok, let me get this clear. You are saying that the game now actually saves, but it onlyu can do it in two slots? I'm a bit confused with this conversation because of the mail respones mess.

nope just in the maker makermatic

**Comment by jeffyjeffy1023** [comment] 2020-07-31 19:42
Oh that's just bullsh*t, but I guess it'll have to do for now.

On Jul 31, 2020 3:01 PM, MixedVictor <notifications@github.com> wrote:

Ok, let me get this clear. You are saying that the game now actually saves, but it onlyu can do it in two slots? I'm a bit confused with this conversation because of the mail respones mess.

nope just in the maker makermatic

**Comment by Voidspades** [comment] 2020-11-03 21:06
Are there any patches for this?

**Comment by RocketRobz** [comment] 2020-11-04 01:13
As soon as one is known and working, it'll be implemented.

**Comment by AM-PM** [comment] 2021-01-30 07:23
I'm quite pissed because I spent 2 hours on 2 separate instances making shit and it being wiped due to the missing nand chip.

**Comment by jeffyjeffy1023** [comment] 2021-01-30 21:22
Y'know, why don't we just emulate the missing NAND chip?

**Comment by RocketRobz** [comment] 2021-01-31 01:22
It's a matter of either patching the right functions, or getting the patched functions to work properly.

**Comment by AM-PM** [comment] 2021-01-31 02:19
The million dollar question here is: Does a patch even exist? Is it possible to mimic NAND via just a patch?

**Comment by RocketRobz** [comment] 2021-01-31 02:26
Yes, it's possible. We're already mimicking the DS Memory Expansion Pak by patching the DS Browser to use the extra NAND of the DSi/3DS.

**Comment by AM-PM** [comment] 2021-01-31 02:35
mbad

**Comment by NigzNogz** [comment] 2021-02-01 12:05
same here
is there a fixed rom with the save fix for my r4 card

**Comment by jeffyjeffy1023** [comment] 2021-02-02 12:03
not yet, no

**Comment by drive-eisnerguy1** [comment] 2021-04-10 08:52
Any progress on solving this?  Would be eternally grateful if this is somehow fixed :D

**Comment by uncletrunks** [comment] 2021-04-26 03:08
Interesting, I don't seem to be running into this issue at all on the latest version. Admittedly I only made a small game to test with and downloaded a couple off of wiimmfi, but it seems to be working as is. Can anyone confirm if this was fixed intentionally? I can get a hash off the rom I'm using if it's possible it's been modified in some way.

**Comment by VictorMX2307** [comment] 2021-04-26 17:14
> Interesting, I don't seem to be running into this issue at all on the latest version. Admittedly I only made a small game to test with and downloaded a couple off of wiimmfi, but it seems to be working as is. Can anyone confirm if this was fixed intentionally? I can get a hash off the rom I'm using if it's possible it's been modified in some way.
> 
> EDIT:
> Here's the md5sum of the rom that I'm using.
> c4e2e4e83634d6dbef3bced08f2d2756 4812 - WarioWare - D.I.Y. (USA).nds

ok im going to try it

**Comment by VictorMX2307** [comment] 2021-04-26 17:19
> > Interesting, I don't seem to be running into this issue at all on the latest version. Admittedly I only made a small game to test with and downloaded a couple off of wiimmfi, but it seems to be working as is. Can anyone confirm if this was fixed intentionally? I can get a hash off the rom I'm using if it's possible it's been modified in some way.
> > EDIT:
> > Here's the md5sum of the rom that I'm using.
> > c4e2e4e83634d6dbef3bced08f2d2756 4812 - WarioWare - D.I.Y. (USA).nds
> 
> ok im going to try it

yep fully working, but im going to try something more

**Comment by VictorMX2307** [comment] 2021-04-26 17:22
ok so i didn't find any problems for now

**Comment by dark9volt** [comment] 2021-04-28 02:08
I've updated my TwilightMenu and i've tried saving a stock and Makermatic microgame, it worked!

I think they should update WW D.I.Y's part on the retail roms compatibility list.

**Comment by RocketRobz** [comment] 2021-04-28 02:14
It seems commit f655efc4 has fixed this!
Additionally, this has been added to the changelog of v0.39.0.

**Closed by RocketRobz** 2021-04-28 02:14 UTC
Labels: Enhancement, Future Work, Retail

**Comment by jeffyjeffy1023** [comment] 2021-04-28 20:49
Finally! :)

**Comment by LimpoIsRad** [comment] 2021-06-06 03:03
It still wont save for me could it be the rom?

**Comment by VictorMX2307** [comment] 2021-06-06 03:04
> It still wont save for me could it be the rom?

update your nds bootstrap

**Comment by AM-PM** [comment] 2021-06-06 03:06
> 
> 
> It still wont save for me could it be the rom?

Is the old save still in the Twilight Menu folder on the SD card? Delete it either by using FBI to do it, or delete it on the computer. As mentioned by Victor, updating the bootstrap, then deleting the old save may fix the issue.

**Comment by LimpoIsRad** [comment] 2021-06-06 03:08
i did it stilll isnt working

**Comment by LimpoIsRad** [comment] 2021-06-06 03:09
(saying i did to both btw)

**Comment by AM-PM** [comment] 2021-06-06 03:10
> 
> 
> (saying i did to both btw)

Delete the old rom and either find a new one or try again by extracting the old rom back into the TwilightMenu Rom Folder.

**Comment by LimpoIsRad** [comment] 2021-06-06 03:12
> > (saying i did to both btw)
> 
> Delete the old rom and either find a new one or try again by extracting the old rom back into the TwilightMenu Rom Folder.

do you have a rom i could use? im very new to 3ds hacking so idk what im doing

**Comment by AM-PM** [comment] 2021-06-06 03:15
https://romsmania.cc/roms/nintendo-ds/4812-warioware-d-i-y-238353 Try here, but remember to only download through the browser when it gives you options to download, as I don't really trust the Download Manager they try to shill you, not that I've tried it.

**Comment by Kaisaan** [comment] 2021-06-06 03:16
Please do not link or ask for ROMs here.

**Comment by LimpoIsRad** [comment] 2021-06-06 03:16
Aw hell nah its a .exe file

**Comment by LimpoIsRad** [comment] 2021-06-06 03:16
> Please do not link or ask for ROMs here.

ok

**Comment by AM-PM** [comment] 2021-06-06 03:17
> 
> 
> Please do not link or ask for ROMs here.

That's what I expected.

**Comment by Kaisaan** [comment] 2021-06-06 03:27
@AM-PM Not a legal expert but I'm pretty sure but linking retail ROMs is against GitHub's Terms of Service (and other stuff like the U.S. Law). We don't want to get any DMCA's so it's best to just assume that there's a no-piracy rule in place and not link stuff in the first place.

@LimpoIsRad Try redumping your ROM. You can then verify if your dump is clean with [dat-o-matic](https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=4812). Make sure that you're running the game in DSi Mode as well.

Because this issue is already closed, please ask for further assistance in the [DS⁽ⁱ⁾ Mode Hacking!](https://discord.gg/yD3spjv) Discord Server.

**Comment by LimpoIsRad** [comment] 2021-06-06 03:31
ive seen the same fucking intro so many times i want to blow my brains out

**Comment by Stack3r** [comment] 2021-06-06 03:32
Language please

**Comment by LimpoIsRad** [comment] 2021-06-06 03:36
> @AM-PM Not a legal expert but I'm pretty sure but linking retail ROMs is against GitHub's Terms of Service (and other stuff like the U.S. Law). We don't want to get any DMCA's so it's best to just assume that there's a no-piracy rule in place and not link stuff in the first place.
> 
> @LimpoIsRad Try redumping your ROM. You can then verify if your dump is clean with [dat-o-matic](https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=4812). Make sure that you're running the game in DSi Mode as well.
> 
> Because this issue is already closed, please ask for further assistance in the [DS⁽ⁱ⁾ Mode Hacking!](https://discord.gg/yD3spjv) Discord Server.

how do i know if im in Dsi mode

**Comment by LimpoIsRad** [comment] 2021-06-06 04:03
this is a dumpster fire for me

**Comment by Peter0x44** [comment] 2021-06-06 04:08
I suggest you instead voice your frustrations in the [DS⁽ⁱ⁾ Mode Hacking!](https://discord.gg/yD3spjv) Discord Server, as you have already been invited to do, instead of on this closed issue.

**Comment by LimpoIsRad** [comment] 2021-06-06 04:15
YO I GOT IT TO WORK THANK YOU AM-PM AND KAISAAN

**Comment by Stack3r** [comment] 2021-06-06 04:18
What was the fix?

**Comment by LimpoIsRad** [comment] 2021-06-06 04:18
trial and error

**Comment by MaymonAdir** [comment] 2021-07-08 05:55
Make sure your nds-bootstrap is updated to latest version and try playing Warioware DIY (4812 version) with NDS forwarder generator. I tried and my game is fully saved 100%
