### ISSUE TITLE
Add support for banner.sav

### ISSUE THREAD

**Issue by AbnormalPoof** [DS-Homebrew/nds-bootstrap#1223] opened 2021-07-30 19:37 UTC
This is so that the Brain Age games work

this is more or less a discussion thread, kinda

**Comment by AbnormalPoof** [comment] 2021-07-30 19:39
i cant really add the enhancement label-

**Comment by RocketRobz** [comment] 2021-07-30 19:46
Duplicate of #1167

**Closed by RocketRobz** 2021-07-30 19:46 UTC
