### ISSUE TITLE
WarioWare: D.I.Y - Distribution Center does not work with Wii

### ISSUE THREAD

**Issue by Naidru** [DS-Homebrew/nds-bootstrap#1260] opened 2021-08-30 20:03 UTC
**Your console:** Nintendo 3DS (CTR-S-USZ-C0)
**Launch Method:** Launched via the SD Card Using TWiLight Menu
**Version used:** relase - v0.46.2
**Game tested/used/applicable:** WarioWare: D.I.Y - UORE

**Expected Behavior:** When using the Distribution Center to connect with a Wii, it should connect perfectly fine and allow you to transfer/exchange "products"
**Actual Behavior:** Able to connect but disconnects after a couple seconds, it disconnects and says "Connection was Interrupted"

### Steps to reproduce

Start up a ROM of WarioWare: D.I.Y. Stored on the SD card and head to the "Distribution Center"
Open WarioWare: D.I.Y. Showcase on the Wii and head to the Distribution Center
Try to connect to the Wii and DS and wait

nds-bootstrap.ini used
[nds-bootstrap.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/7079305/nds-bootstrap.zip)

### Logs
```
findModuleParamsOffset:
Module params offset restored: 02000BB8
sdk_version: 04027539
arm9 is not compressed

Switched to NTR mode BIOS
relocate_ce9
firstCardLocation 023F0000 : 02780000

armReadCardLocation 023F00F0 : 02780000

thumbReadCardLocation 023F0110 : 02780000

armReadCardDmaLocation 023F0140 : 02780000

armReadSlot2Location 023F0164 : 02780000

armSetDmaCardLocation 023F0194 : 02780000

thumbReadCardDmaLocation 023F01C0 : 02780000

thumbSetDmaCardLocation 023F01E0 : 02780000

armReadNandLocation 023F0204 : 02780000

thumbReadNandLocation 023F0228 : 02780000

armWriteNandLocation 023F0240 : 02780000

thumbWriteNandLocation 023F0260 : 02780000

armIrqEnableLocation 023F0290 : 02780000

thumbIrqEnableLocation 023F02B0 : 02780000

pdashReadLocation 023F02DC : 02780000

thumbReadSlot2Location 023F0300 : 02780000

ipcSyncHandlerLocation 023F0368 : 02780000

resetLocation 023F0390 : 02780000

globalCardLocation 023F14E0 : 02780000

 ce9->patches 023F0034

patchCardNds

cardIrqEnable location : 0209281C

startOffset : 02003800

cardRead location : 0209D838
023F0000

swi12 location : 020004CC

cardPullOut location : 0209DC40

cardId location : 0209D928


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 0209D588


NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 0209D624

patchMpuSize: 00000000

Mpu2 init: 0209432C

ERR_NONE

cardIrqEnable location : 02383B0C

forwardedRelocStartAddr
02380204
vAddrOfRelocSrc
0238021C
Relocation src: 0238021C
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 0238B5F0
Eeprom read:	0238B5FC
Eeprom page write:	0238B610
Eeprom page prog:	0238B624
Eeprom verify:	0238B638
Eeprom page erase:	0238B648
swiHalt location : 02380694

swi12 location : 0238BA30

swiGetPitchTable location : 02386FE8

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238F780

ERR_NONE
hookLocation arm9: 027E0000

ROM loaded into RAM

AP-fix found
AP-fix applied
chipID: 80007FC2
```              

### Other notes
**N/A**

**Comment by NightScript370** [comment] 2021-09-24 09:15
https://github.com/DS-Homebrew/nds-bootstrap/issues/415
Duplicate of this issue? @RocketRobz

**Comment by Naidru** [comment] 2021-09-24 14:21
NDS-Bootstraper doesn't crash. It just connects then a few seconds later, says that connection was lost

**Comment by xXIN51Xx** [comment] 2021-11-14 14:57
I also have this issue

Your console: New Nintendo 3DS XL (RED-S-USZ-C1)
Launch Method: Launched via the SD Card Using TWiLight Menu
Version used: relase - v0.50.2
Game tested/used/applicable: WarioWare: D.I.Y

I tried about 10 times and couldn't get a stable connection, connects then after 5 seconds it disconnects

**Comment by spamvoxel** [comment] 2021-12-31 15:04
I’m having the same exact problem and going as fast as I can, but still nothing. I guess I’d better keep trying

**Comment by RocketRobz** [comment] 2022-08-11 08:13
The issue should hopefully be fixed starting with v0.63.0.

**Comment by Sukotto-1999** [comment] 2023-09-01 01:12
I tried distribution center in WarioWare DIY with latest NDS-bootstrap and Wimmfi patched WarioWare DIY Showcase, the game did not freeze when WarioWare DIY detects a Wii and WarioWare DIY Showcase detects a DS. But the game freezes after saving when transferring microgame on the Wii to the DS. But the only issue i have with my R4 cart was WarioWare DIY freezes on unmodified game due to anti-piracy, but i patched it and it works, the only issue i have is it hangs when going to the Distribution Center. Maybe any help on R4?

**Comment by Sukotto-1999** [comment] 2023-09-10 17:59
Well, i tried it with version 1.0.0 with the Golden Sun fix, and the game does not freeze when saving at this time! Hopefully it should work now. If issue appears again. Reopen. THX @RocketRobz

**Closed** 2023-09-11 12:44 UTC
Labels: Bug, Retail
