### ISSUE TITLE
Load GBA rom and save as an emulated Slot-2 for DS games that support loading GBA content.

### ISSUE THREAD

**Issue by ccfman2004** [DS-Homebrew/nds-bootstrap#996] opened 2020-08-11 20:48 UTC
Is your feature request related to a problem? Please describe.
Would it be possible to hook a GBA rom and save into an emulated slot-2 for games like Pokemon Diamond and Pearl that use the GBA Pokemon games to transfer Pokemon?

Describe alternatives you've considered
Currently the only way to do this is to use 3DS app called PKSM to export the Gen 3 Pokemon and import them into the Gen 4 games. I would prefer to do it as the game intends as sometimes there are issues with PKSM changing the Pokemons info.

**Comment by ccfman2004** [comment] 2020-08-11 23:10
Maybe we could also hook into GBA VC games both official and custom.

**Comment by Kaisaan** [comment] 2022-02-22 05:40
Duplicate of #19, closing.

**Closed by Kaisaan** 2022-02-22 05:40 UTC
Labels: Enhancement
