### ISSUE TITLE
Metroid Prime Hunters Download Mode and Local Mode not working

### ISSUE THREAD

**Issue by LuFerLu** [DS-Homebrew/nds-bootstrap#1719] opened 2024-07-13 02:49 UTC
### Game Console(s) used

- [ ] Nintendo DS
- [X] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [X] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD Card. TWiLight Menu++ v27.5.2

### Version used

nds-bootstrap 1.5.4

### Game tested/used/applicable

Metroid Prime Hunters NTR-AMHE-USA Revision 1
MD5: 9fe5f1eb1eb9dc5d90130408f813b39e
SHA1: a8679d4f8dcb445cbe946a424241ef44901b0caf

### Expected Behavior

Should have not disconnected from the host

### Actual Behavior

The 3DS that downloaded the rom gets past the nintendo logo and tries to download the game but after a while it gets disconnected from the host.

### Steps to reproduce

Start a Metroid Prime Hunters single card game. Download the game from another DS. Continue until it fails.

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = 284
USE_ROM_REGION = 1
NDS_PATH = sd:/roms/nds/Metroid Prime - Hunters (USA) (Rev 1).nds
SAV_PATH = sd:/roms/nds/saves/Metroid Prime - Hunters (USA) (Rev 1).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 1
DSI_MODE = 1
BOOST_CPU = 1
BOOST_VRAM = 0
CARD_READ_DMA = 0
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH =
HOMEBREW_ARG =

### Logs

Loading the NDS file...
Header CRC is valid!
Module params offset: 02004B68
sdk_version: 03004E86
arm9 is compressed
Secure area already decrypted
Switched to NTR mode BIOS
Cloneboot detected
patchCardNds

cardIrqEnable location : 02085704

startOffset : 02004000

Mpu start: 02004A88

Mpu data: 02004B1C

Mpu init: 0208817C

Mpu data alt: 02087EC4

Mpu start 2: 02004A90

Mpu data 2: 02004B20

Mpu init 2: 02088184

waitCpuCycles location : 02088BA4

cardRead location : 020921CC
03700000

cardPullOut location : 020929B4

cardId location : 02092168

patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 02092508

NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 02092468

reset location : 02088BC4

ERR_NONE

Sleep location : 0238E160

cardIrqEnable location : 02383DE4

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 023801B0
Relocation dst: 037F8000
RAM mirror check location : 0238015C

Arm7 (patch v2)
cardReadEndAddr: 0238C08C
cardstructAddr: 03809CE0
readCacheEnd: 0238C1C8
JumpTableFunc: 0238C1CC
returned_A0_with_MKDS: 0238C26C
addrOfSomething_85C0: 0238BB70
anotherLocinA7WRAM: 0380A304
amal_8CBC: 0238C26C
aFinalLocation: FE38C250
Eeprom protect:	0238C2AC
Card id:	0238C2B4
Card read:	0238C2D4
Eeprom read:	0238C2EC
Eeprom page write:	0238C304
Eeprom page prog:	0238C31C
Eeprom verify:	0238C334
Eeprom page erase:	0238C344
swi12 location : 0238C7B0

swiGetPitchTable location : 02387724

ERR_NONE

Card patch successful

hookNdsRetailArm7
hookLocation arm7: 0239032C

ERR_NONE
hookLocation arm9: 027E0008

Part of ROM pre-loaded into RAM
chipID: 00003FC2            

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment] 2024-07-13 04:33
The issue is caused by card read DMA on the 3DS side. In TWLMenu++, press Y to open the per-game settings menu, then turn off `Card Read DMA`.

**Comment by LuFerLu** [comment] 2024-07-13 18:33
Tried with that and TWL speed since it said that in the other github issue but it still didnt work.

**Comment by RocketRobz** [comment] 2024-07-13 19:35
> Tried with that and TWL speed since it said that in the other github issue but it still didnt work.

Then you'll need to try again, once you get the error.

**Comment by RocketRobz** [comment] 2024-09-03 01:46
Fixed as of v1.6.0.

**Closed by RocketRobz** 2024-09-03 01:46 UTC
