### ISSUE TITLE
0.31.0 Compatibility Issues 

### ISSUE THREAD

**Issue by Monalisashusband** [DS-Homebrew/nds-bootstrap#894] opened 2020-03-19 12:40 UTC
Compatibility is on an all time high, only Golden Sun Dark Dawn and Pokemon Dash are the remaining mainstream games not working, very good job ahezard and Rocket Robz!

Some games may need specific settings to work in 0.31.0 like SM 64 DS has to be on nightly, Last Window has to have AP usrcheat.dat code enabled, Summon Night X English Patch has to be manually patched with xdelta, etc. 

I have tested almost all games due to COVID 19!!! From boot to at least the first savepoint/check point of the game/s and found the issues below:

Console: O3DS XL
Launch Method: Luma CFW
Version used: 0.31.0 Nightly and Release
Game tested/used/applicable (please note all possible game settings and game setting combinations have been used, also got the roms from multiple sources to validate): 
- Top Spin USA and EU (clean/unpatched/untrimmed)
- Panzer Tactics USA and EU (clean/unpatched/untrimmed)
- Marvel's Trading Card Game USA and EU (clean/unpatched/untrimmed)
- Ni No Kuni JP (English patched/AP usrcheat.dat code enabled)

Actual Behavior:
Top Spin -> Black screen on top, White screen on bottom. Cannot be soft reset or reset to TWiLight Menu
Panzer Tactics ->  White screen for both can be soft reset and reset to TWiLight Menu
Marvel's Trading Card Game -> White screen for both can be soft reset and reset to TWiLight Menu
Ni No Kuni -> Black screen on top, White screen on bottom. Cannot be soft reset or reset to TWiLight Menu

Steps to reproduce
Normally boot the .nds files via TWiLight Menu++ and nds bootstrap

**Comment by Monalisashusband** [comment] 2020-03-19 15:48
Just to add, though I know this has been in the regression list, Draglade US and EU is booting to white screen as well

**Comment by IrisHeartCPU** [comment] 2020-03-19 16:14
Have you tested the SaGa 3 JP (eng translation)?
The game it isn't compatible in earlier versions.

**Comment by Monalisashusband** [comment] 2020-03-19 16:22
@IrisHeartCPU works fine all the way to the first part you can control the character, have not played the game to an extent, but I'll report back.

**Comment by Monalisashusband** [comment] 2020-03-19 16:33
@IrisHeartCPU on second thought, freezes still after all commands in the first battle #271 still stands true

**Comment by Monalisashusband** [comment] 2020-03-19 18:40
Only got this far on SaGa 3 before it crashed with a red screen on the bottom (crashed after the dialogue after the first battle)
![1](https://user-images.githubusercontent.com/56161262/77102447-cf3e0700-6a53-11ea-92e1-c6f4470c2861.jpg)
![2](https://user-images.githubusercontent.com/56161262/77102474-d9f89c00-6a53-11ea-99c0-c2121286eac2.jpg)
![3](https://user-images.githubusercontent.com/56161262/77102520-ec72d580-6a53-11ea-8fe4-18da2c78b546.jpg)

**Comment by Kaisaan** [comment] 2020-03-20 19:20
Super Mario 64 DS (USA) Works fine on version 0.31.0 on my N2DS XL, but only works on nightly on my DSi XL as you said. Ni No Kuni also works fine on my N2DS XL without any cheats applied.

**Comment by Monalisashusband** [comment] 2020-03-21 01:04
@Kaisaan didn't think ndsbootstrap and twilight menu would behave differently between o3ds and n3ds, but it could be the case. 

Anyway this could also be a point of reference for those that have the same specs as myself (or DSi for your case). These are the games that would not work on 0.31.0 unless played on specific settings (I will post the settings later):

007 Quantum of Solace US
Animal Crossing Wild World US
Glory of Heracles
Last Window The Secret of Cape West EU
Okamiden US
Summon Night X Tears Crown JP w/ English Translation
Super Mario 64 DS US
Transformers War for Cybertron Autobots & Decepticons US

If anyone can add more to the list, feel free I am still checking from my library (all games listed in the compatibility list and more)

**Comment by Kaisaan** [comment] 2020-04-03 16:35
With 0.32.0 now being the latest version of nds-bootstrap, I'd suggest retesting all of these games and also update the compatibility sheet accordingly.

**Comment by IrisHeartCPU** [comment] 2020-04-04 15:37
Tested Golden Sun Dark Dawn with nds-bootstrap 0.32.0, results: as always, boots to a black screen.
I don't have more games that don't work, so i can't test them.

**Comment by woozuz** [comment] 2020-04-07 10:37
Draglade is now playable although I’m experiencing slight performance issues (loading times between screens averaging 20 seconds, some lag in bullet menu). Can anyone else help test the game and confirm if it’s working fine on their end?

**Comment by Kaisaan** [comment] 2020-04-12 02:46
@Monalisashusband you said that you will be posting the specific settings for each of the games that you said do not work. When do you plan on posting the settings? Also, do these issues still occur on the latest version of nds-bootstrap (which is now 0.32.1)?

**Comment by Keptjup** [comment] 2020-04-14 03:04
> Draglade

hey how did u get draglade to work?? because mine is still on blackscreen whenever i load it, i have twilightmenu++ , can u pls tell me the steps i need to do to make it work

**Comment by Keptjup** [comment] 2020-04-18 22:00
draglade works on new version of bootstrap 0.32.1

**Comment by RocketRobz** [comment] 2020-04-18 22:12
Actually, the latest version is v0.33.0.

**Comment by Keptjup** [comment] 2020-04-18 22:19
> Actually, the latest version is v0.33.0.

Oke got it wil update it, thanks xD

**Comment by Kaisaan** [comment] 2020-05-28 17:20
@Monalisashusband with 0.35.1 being the latest version of nds-bootstrap, how are all these issues now?

**Comment by Pixead** [comment] 2020-08-09 15:26
I don't know about the others but I can confirm that transformers work on the latest nds bootstrap version

**Comment by geogolem** [comment] 2020-08-11 19:03
I tried Saga 3 with English patch with TwilightMenu++ v16.1.0 (and associated NDSBootstrap). I still get the freeze once you input all the commands in the first battle.

**Comment by rs1n** [comment] 2020-10-05 15:42
With 0.35.1 Ni No Kuni English translation still results in a black top screen and white bottom screen. This was tested on both the New 3DS XL and the 3DS XL (not "New"), as well as a DSi XL using a default installation of TwiLightMenu++. No usercheat.dat used (can test with usercheat.dat if someone wants to clue me in to how that is set up for this specific game; did not find such a file in the installation, though).  SHA-1 for original ROM was: 

DFAAA4DC03BBB59F010B9146A720B24CFC7738EB

Post-patch, the SHA-1 hash is:

1D3A1366427F31480AA939521C1C8BAC5BBB9F86

**Comment by RocketRobz** [comment] 2020-10-05 15:44
@rs1n You need to use [this](https://mega.nz/#!7L4ETILL!yguPzZpB4PvVk5qU2JFm1X5MoWbKQrH9bqUHU-1hQ9M) patch for it to work in nds-bootstrap.

**Comment by rs1n** [comment] 2020-10-06 15:44
@RocketRobz Thank you for the patch files. I just tested it out and it works fine, now. Thank you for all that you do!

**Comment by Kaisaan** [comment] 2021-04-21 19:32
With nds-bootstrap version [v0.39.0](https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v0.39.0) being the latest version, the issue topic name is getting more outdated. @Monalisashusband I suggest you update nds-bootstrap and TWiLight Menu++ and test to see if these issues still occur. If there are still issues, I suggest creating individual issue pages for each game so it is easier to manage. Closing this now.

**Closed by Kaisaan** 2021-04-21 19:32 UTC
Labels: Bug, Major, Retail
