### ISSUE TITLE
DSiware from SD on 3DS

### ISSUE THREAD

**Issue by DraconicNEO** [DS-Homebrew/nds-bootstrap#1067] opened 2021-01-28 04:20 UTC
**Your console:** 3DS
**Launch Method:** Luma3DS
**Version used:** Release
**Game tested/used/applicable:** Not Specific
**Expected Behavior:** Loads DSiware
**Actual Behavior:** NDS Bootstrap says an Error occurred 

### Steps to reproduce
Load DSiware

### Logs

N/A

### Other notes

Hello I wanted to ask what causes the issue of DSiware not loading from NDS bootstrap on 3DS. I know it seems to work fine on DSi. Is there any issues exclusive to 3DS or was this an intentional choice by chance? Also Please let me know if this issue is specific to Twilight Menu ++ so I can make a post there.

**Comment by RocketRobz** [comment] 2021-01-28 04:24
Some DSi functions are not patched, causing DSi-Enhanced and DSiWare games to not boot in DSi mode.

Duplicate of #300

**Closed by RocketRobz** 2021-01-28 04:24 UTC

**Comment by DraconicNEO** [comment] 2021-01-28 06:09
> 
> 
> Some DSi functions are not patched, causing DSi-Enhanced and DSiWare games to not boot in DSi mode.
> 
> Duplicate of #300

Glad to see someone already brought this up.
