### ISSUE TITLE
pokemon heartgold crash after updating

### ISSUE THREAD

**Issue by xXBindingOfDanXx** [DS-Homebrew/nds-bootstrap#1376] opened 2022-03-10 16:53 UTC
**Your console:**
dsi

**Launch Method:**
twilight menu from sd card

**Version used:**
latest release 0.54.2

**Game tested/used/applicable:**
pokemon heard gold

**Expected Behavior:**
game boots fine

**Actual Behavior:**
game crashes after nds-bootstrap screen

### Steps to reproduce
1. open twilight
2. open game
3. wait for the crash

### nds-bootstrap.ini

```[NDS-BOOTSTRAP]
DEBUG = 1
LOGGING = 1
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 0
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
NDS_PATH = sd:/roms/nds/PKHG.nds
SAV_PATH = sd:/roms/nds/saves/PKHG.sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = 5
REGION = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
HOMEBREW_ARG =
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
ASYNC_CARD_READ = 0
APP_PATH = sd:/DSSOUN~1.NDS
PRV_PATH = sd:/SAVES/DSSOUN~1.PRV
GAME_SOFT_RESET = 1
SWI_HALT_HOOK = 0
B4DS_MODE = 0
USE_ROM_REGION = 1
```

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/8225347/NDSBTSRP.LOG)

been using twilight for a while on an old version i updated yesterday and now game won't boot

**Comment by JonArcherII** [comment] 2022-03-10 17:34
What do you mean by crash? I have been playing Heartgold on the latest release without issues.

**Comment by Allinxter** [comment] 2022-03-10 17:59
HeartGold also runs fine on my end, but a copy I have that's patched with SacredGold and is running into this exact issue.
Is your rom patched? If not, could you verify if your dump's hashes match the hashes a trusted dump on [No Intro's Database](https://datomatic.no-intro.org/index.php?page=search&s=28) would have?

You can use [GM9i](https://github.com/DS-Homebrew/GodMode9i/releases/download/v3.2.0/GodMode9i.7z) on your console, or 7zip on a PC to calculate the hash.

**Comment by xXBindingOfDanXx** [comment] 2022-03-10 21:19
> What do you mean by crash? I have been playing Heartgold on the latest release without issues.

the logo appears then it fades to white and stays like that until i restart



> HeartGold also runs fine on my end, but I have a copy that's patched with SacredGold and is running into this exact issue. Is your rom patched? If not, could you verify if your dump's hashes match the hashes a trusted dump on [No Intro's Database](https://datomatic.no-intro.org/index.php?page=search&s=28) would have?
> 
> You can use [GM9i](https://github.com/DS-Homebrew/GodMode9i/releases/download/v3.2.0/GodMode9i.7z) on your console, or 7zip on a PC to calculate the hash.

what am i supposed to do on the database? i got 62cf70a804a2b844af0d77008cf66e7ba59e100 from the calculate sha1 option in godmode what do i do with this

**Comment by RocketRobz** [comment] 2022-03-10 23:10
Game boot fine on my side, and cannot reproduce, so closing.
If you need further assistance, please join our Discord server.

**Closed by RocketRobz** 2022-03-10 23:10 UTC
Labels: Retail, Cannot reproduce
