### ISSUE TITLE
Wario Ware D.I.Y Microgames don't save

### ISSUE THREAD

**Issue by OfficialNova** [DS-Homebrew/nds-bootstrap#862] opened 2020-02-16 00:08 UTC
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi XL
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) Unlaunch only Ver 2.0
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Wario Ware D.I.Y

### Expected behaviour

Microgames are supposed to be shipped and put on the D.I.Y shelf

### Actual behaviour

Ships but nothing appears on the shelf

### Steps to reproduce

1.Make a microgame
2.Ship it
3.Go to the D.I.Y shelf

**Comment by Kaisaan** [comment] 2021-04-21 11:24
This seems to be a duplicate of #306 which is still open. Going to close this.

**Closed by Kaisaan** 2021-04-21 11:24 UTC
