### ISSUE TITLE
Mario vs. Donkey Kong: Mini-Land Mayhem! sprites invisible

### ISSUE THREAD

**Issue by songokuemumania** [DS-Homebrew/nds-bootstrap#1112] opened 2021-03-28 20:42 UTC
**Your console: new 3DS XL** 
**Launch Method:luma 10.2.1** 
**Version used: bootstrap 0.38.0** 

**Game tested/used/applicable:Mario vs. Donkey Kong: Mini-Land Mayhem! USA rom** 

**Expected Behavior: mario should show up on scren** 
**Actual Behavior: mario is there but invisible**

**Comment by RocketRobz** [comment] 2021-03-28 20:47
Duplicate of #467

**Closed by RocketRobz** 2021-03-28 20:47 UTC
