### ISSUE TITLE
I can't transfer pokemon from Platinum/Pearl/Diamond to Pokemon Battle Revolution (Wii)

### ISSUE THREAD

**Issue by MisterAcro** [DS-Homebrew/nds-bootstrap#1505] opened 2022-12-14 01:33 UTC
**Your console: Nintendo DSi XL, Blue color**

**Launch Method: Via SD Card, I use Twilight Menu v25.6.1 and Unlaunch.**

**Version used: NDS-Bootstrap Release, v0.67.0**

**Game tested/used/applicable: Pokémon Platinum (DS) and Pokémon Battle Revolution (Wii)**

**Save file:**
[Save file and ini file.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/10223368/Save.file.and.ini.file.zip)

**Expected Behavior: The game must let you transfer the pokemon to the Wii game.**

**Actual Behavior: When I connect the DS with the Wii, and the DS shows the logo of Pokémon Battle Revolution, it says "Can't access to the save file"**

### Steps to reproduce
1. Turn on the consoles, the Wii and the DS
2. Enter to the game "Pokémon Battle Revolution" on the Wii, and enter to "Pokémon Diamond/Pearl/Platinum" on the DS, via Twilight Menu and NDS-Bootstrap
3. On the Wii, select "Colosseum mode", then, go to "Storage", "Copy Pokémon", press the button for copying pokémon and go to your DS
4. On the DS, select "Connect to Wii", then, wait for both consoles to connect
5. When they finish to connect, the logo of "Pokémon Battle Revolution" should be shown, and then, a message saying that can't access to the save file where the pokemon are.

### nds-bootstrap.ini

```
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 3
DMA_ROMREAD_LED = 3
PRECISE_VOLUME_CONTROL = 1
SDNAND = 1
MACRO_MODE = 0
SOUND_FREQ = 1
CONSOLE_MODEL = 0
HOTKEY = 18c
NDS_PATH = sd:/roms/nds/Pokemon - Edicion Platino [NDS] [Roms Nintendo en Español].nds
SAV_PATH = sd:/roms/nds/saves/Pokemon - Edicion Platino [NDS] [Roms Nintendo en Español].sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = es
LANGUAGE = 5
REGION = -1
DSI_MODE = 2
BOOST_CPU = 0
BOOST_VRAM = 1
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 1
AP_FIX_PATH =
HOMEBREW_ARG =
DONORTWLONLY0_NDS_PATH = nand:/title/00030005/484e4b45/content/00000002.app
SLEEP_MODE = 1
APP_PATH = sd:/ROMS/DSIWARE/GAME_&~1.NDS
PRV_PATH = sd:/ROMS/DSIWARE/SAVES/
GAME_SOFT_RESET = 1
```

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/10223386/NDSBTSRP.LOG)

### Other notes
Ok, I know this includes a Wii game, which is something that is not related to NDS-Bootstrap, but, if you can help, i would be appreciated...

### Will you be available for future issues and/or replies?
Yes, of course!

**Comment by RocketRobz** [comment] 2022-12-14 01:34
Duplicate of #415

**Comment by RocketRobz** [comment] 2022-12-14 01:34
> if you can help, i would be appreciated...

Currently, the only solution is to run the game from a flashcard.

**Closed by RocketRobz** 2022-12-14 01:34 UTC

**Comment by MisterAcro** [comment] 2022-12-14 01:36
> > if you can help, i would be appreciated...
> 
> Currently, the only solution is to run the game from a flashcard.

The other thing, is that i don't have a flashcard...
But, could you dev guys, try to do something with that? Or... Is very complicated?

**Comment by RocketRobz** [comment] 2022-12-14 01:38
It is currently unknown how to fix the issue.

**Comment by MisterAcro** [comment] 2022-12-14 01:42
> It is currently unknown how to fix the issue.

Oh, crap.
