### ISSUE TITLE
Launch Mario Kart DS Kiosk Demo USA Version

### ISSUE THREAD

**Issue by Alexis20000** [DS-Homebrew/nds-bootstrap#1677] opened 2024-02-11 19:54 UTC
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [X] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD Card with Twilight Menu ++

### Version used

Release

### Game tested/used/applicable

Twilight Menu ++

### Expected Behavior

If you trying to Launch mario kart ds kiosk demo Usa Version = you are on a white screen

### Actual Behavior

Impossible to launch a kiosk demo of a game

### Steps to reproduce

Go to launch a demo mkds kiosk demo usa version and launch = white screen

### nds-bootstrap.ini

Nds-bootstrap.ini n'est pas présent a cause de twl-menu++ / twilight-menu++

### Logs

No log

### Other notes

No other information

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment] 2024-02-11 20:01
You did not fill up those sections correctly:
- Version used: `Release` is not helpful. Please mention the actual version you're using.
- Game tested/used/applicable: TWiLight Menu++ is what tells nds-bootstrap to boot your game, which in this case, is the Mario Kart DS Kiosk Demo.
- Expected Behavior: It sort-of the same as "Actual Behavior". You need to say what you expected to happen, like "The game should work properly".
- nds-bootstrap.ini: You mention that it's not present because you use TWLMenu++. That is not true. TWiLight Menu++ uses nds-bootstrap to boot DS(i) games from the SD card. Are you sure you checked `sd:/_nds/`?
- Logs: You mention there's no log. Did you turn on the `Logging` setting in the nds-bootstrap page of TWLMenu++ Settings?

**Comment by RocketRobz** [comment] 2024-03-01 07:48
Closing due to lack of post update or reply.

**Closed by RocketRobz** 2024-03-01 07:48 UTC
