### ISSUE TITLE
Dragon Quest V Title Loop

### ISSUE THREAD

**Issue by Zanzarglas** [DS-Homebrew/nds-bootstrap#1589] opened 2023-07-05 10:02 UTC
**Your console: New Nintendo 2DS XL**

**Launch Method: SD Card/ Twilight Menu++/ NDS Forwarder** 

**Version used: 0.72.1**

**Game tested/used/applicable:**
<html><body>

CRC |   | 6f455159
-- | -- | --
MD5 |   | a4fa4d54864b14829cdbe2fb53b2bb94
SHA1 |   | 0f11ff6fcd9ef150c620a5fe071b30f80a7a2e40
Verified |   | 2023-06-28

</body>
</html>

**Save file: No Save file, game can't get far enough to create one.**

**Expected Behavior: Game should start and play correctly,**

**Actual Behavior: Cannot get past title screen to start the game. Infinite loop.**

### Steps to reproduce
1.  Start Game
2.  Watch it loop
3. Get sad

**Comment by powderoo** [comment] 2023-07-05 11:12
I woke up this morning and had the same problem. Replaced the bootstrap files to the previous version 0.72.0 and now it proceeds as normal past the title screen.

**Comment by RocketRobz** [comment] 2023-07-08 17:51
Duplicate of #1354

**Closed by RocketRobz** 2023-07-08 17:51 UTC
