### ISSUE TITLE
Golden Sun: Dark Dawn

### ISSUE THREAD

**Issue by chronoss09** [DS-Homebrew/nds-bootstrap#1624] opened 2023-09-09 22:01 UTC
I see this line on the last update : Removed broken AP-fix for Golden Sun: Dark Dawn, as nds-bootstrap now properly handles the patching.

It's means Golden Sun: Dark Dawn now working ?

**Comment by Dartz150** [comment] 2023-09-09 22:05
Yo clearly missed the last update tag, and yes, it works now

https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v1.0.0

**Comment by RocketRobz** [comment] 2023-09-09 23:21
Duplicate of #252

**Closed by RocketRobz** 2023-09-09 23:21 UTC
