### ISSUE TITLE
3DS（To switch the game）（soft reset fail）

### ISSUE THREAD

**Issue by AK580** [DS-Homebrew/nds-bootstrap#1458] opened 2022-09-21 00:34 UTC
I have one N3dsll，
The TW++ is installed，
When I want to quit the NDSgame
I press the L+R+↓+B button，
TM++ Just shut it down，
Back to the main screen of 3DS，
Very few ROMs can be returned to the main screen of TM++，
It's a problem for me，
I don't know if it has anything to do with my use of Chinese-NDSrom,
Please help me.

I tried to enlist the help of TM++ writers，
It might have something to do with "NTS-bootstrap," he told me，
I wonder if anyone has ever been in my situation，
And ask for help. Thank you，

**Comment by agufungus** [comment] 2022-09-21 06:45
I can confirm to have this problem, too. When I select "Quit Game", I expect it to take me back to TWLM++, and instead it shuts off the system, and if the flashcard is loaded on a 3DS, it instead takes me directly back to the 3DS's menu.

**Comment by NightScript370** [comment] 2022-09-22 03:16
Please, for both @AK580 & @agufungus, let me know which ROMs you've tried and worked, and which ones you've tried and not worked. However, there is something I must tell to each individually:

- @AK580: Truth be told, I highly doubt this has been tested on Chinese ROMs by our team because we don't really have access to them ourselves (legally).
- @agufungus: Please let me know what you initially tested this on so that it "shuts off the system". Do you mean a flashcard on a original Nintendo DS

**Comment by agufungus** [comment] 2022-09-22 04:10
OK, the games I tested on so far are:
Newer Super Mario Bros. DS
Super Mario 64 DS
New Super Mario Bros.
Namco Museum DS
Mario Kart DS
Kirby Canvas Curse
Cartoon Network Racing
Super Princess Peach
Sonic Rush Adventure
Kirby Super Star Ultra

And yes, I mean a flashcard on a original Nintendo DS.

**Comment by AK580** [comment] 2022-09-23 01:36
I tested some ROMs,
Both Chinese ROM and original ROM are available.
only
"Assassin's Creed II -- Discovery (USA)
(dubbing changed to Chinese)"
can return to the TW++ home screen.

All the rest of the roms will exit TW++ and go back to the 3DS home screen,
including
Super Mario 64 DS (Korea)
Super Mario 64 DS (Japan)
Super Mario 64 DS (USA)
New Super Mario Bros. (USA)
New Super Mario Bros. (Japan)
New Super Mario Bros. (Hacker Chinese)
.
And all versions of some of the most common games on the NDS,
What I don't understand is,
"Assassin's Creed II -- Discovery (USA)
(dubbing changed to Chinese)"
Why is it so different?

**Comment by DemnyxOnyxfur** [comment] 2022-09-26 16:44
I've been having the same issue with this, but it seems like only on my N3DSXL. My DSiWare roms behave as expected, returning to TwilightMenu++, however I've yet to return to TM++ successfully with any of my DS roms. I've reinstalled cleanly multiple times on the N3DSXL, tried Nightlies, and the issue persists. I have two logs I'll add; one is of a DS game, and the other is of a DSiWare rom. Hoping these help, and I'm also hoping this isn't a wide-spread issue.
[NDSBTSRP-dsirom.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/9648094/NDSBTSRP-dsirom.LOG)
[NDSBTSRP-dsrom.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/9648095/NDSBTSRP-dsrom.LOG)

**Comment by Just4Link** [comment] 2023-05-04 18:48
I have a N3DS with Luma 1.2.0.1 and TwilightMenu++ 25.9.4. Same behavior here .. when i try to exit a game through ingame menu Down+L+Select and L+R+Down+B it will bring me back to the 3DS home screen instead to the TwilightMenu++

**Comment by RocketRobz** [comment] 2023-05-04 20:44
> I have a N3DS with Luma 1.2.0.1 and TwilightMenu++ 25.9.4. Same behavior here .. when i try to exit a game through ingame menu Down+L+Select and L+R+Down+B it will bring me back to the 3DS home screen instead to the TwilightMenu++

Is your console region-changed?

**Comment by Just4Link** [comment] 2023-05-05 05:18
No, its a europe console. In luma is patching disabled. i followed straight 3ds.hacks.com

**Comment by RocketRobz** [comment] 2024-09-03 02:06
Closing, as this is not an nds-bootstrap issue, if the issue happens every time.

**Closed by RocketRobz** 2024-09-03 02:06 UTC
Labels: Bug, Retail, 3DS
