### ISSUE TITLE
Pokemon save will turn my dsi screen black using twlightmenu 

### ISSUE THREAD

**Issue by kavlonator** [DS-Homebrew/nds-bootstrap#1702] opened 2024-05-12 17:59 UTC
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [X] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD card

### Version used

nds-bootstrap ver. release v1.4.1 
twlmenu ++ v26.9.0

### Game tested/used/applicable

Pokemon SoulSilver

### Expected Behavior

load save

### Actual Behavior

after selecting save both screens on ndsi go black 

### Steps to reproduce

save a game on pokemon soulsilver and try loading it

### nds-bootstrap.ini

.

### Logs

.

### Will you be available for future issues and/or replies?

yes

**Comment by RocketRobz** [comment] 2024-05-12 19:55
Duplicate of #1468

**Closed by RocketRobz** 2024-05-12 19:55 UTC
