### ISSUE TITLE
Kingdom Hearts 358/2 getting multiplayer error

### ISSUE THREAD

**Issue by Drakyem** [DS-Homebrew/nds-bootstrap#797] opened 2019-10-28 17:15 UTC
I've been playing this for a while and I haven't got any errors, and a friend and I even played multi without any difficulties. But we uploaded nds-bootstrap and TWiLightMenu (release and nightly) and started getting connection errors. When any of us create a group and select a character, the menu shows up (to select misions, panels, etc) and then we get the "connection error". Why does this happen? I thought multicard games didn't have any problems :/

**Comment by SleepyLark** [comment] 2019-10-28 17:45
May be related to #794, try changing it to "DS Mode" (clock speed to NTR) or using an older version.

**Comment by Drakyem** [comment] 2019-10-28 19:04
Ok, so I "un-updated" TWiLightMenu (to v10.0.1) and nds-bootstrap (to v0.25.2) and it worked! Thank you very much

**Comment by RocketRobz** [comment] 2019-10-28 19:22
Please re-update TWLMenu++ to the latest, but keep the current nds-bootstrap version.

**Comment by Drakyem** [comment] 2019-10-28 20:48
> 
> 
> Please re-update TWLMenu++ to the latest, but keep the current nds-bootstrap version.
I just did it but it keeps giving me the same error :/ - I'm gonna use the other one then...

**Comment by SleepyLark** [comment] 2019-10-28 20:56
Sorry, I should have specified that you only needed to downgrade the nds-bootstrap version, not necessarily the entire TWLMenu++

**Comment by Drakyem** [comment] 2019-10-28 20:58
Don't worry, doing that fixed it!

**Comment by Jerdo32** [comment] 2020-04-19 23:34
I think it's because it's not AP patched, that was my situation and then I could play multiplayer.

**Comment by RocketRobz** [comment] 2020-04-19 23:35
The games are automatically AP-patched though.

**Comment by Jerdo32** [comment] 2020-04-19 23:39
That's also true... But then what could be the cause? 
(Also, I tested with a physical game and another using nds bootstrap, maybe that has to do with it.)

**Comment by RocketRobz** [comment] 2022-02-22 03:25
Haven't encountered any multiplayer errors on my side recently. Closing.

**Comment by dreamsyntax** [comment] 2022-07-16 17:29
This has regressed - this issue exists in v0.61.3

**Comment by RocketRobz** [comment] 2022-07-16 21:19
Nothing multiplayer-related was changed in v0.61.3, so maybe it has regressed before then.
Try turning off card read DMA in the per-game settings menu.

**Comment by dreamsyntax** [comment] 2022-07-17 05:51
> Nothing multiplayer-related was changed in v0.61.3, so maybe it has regressed before then. Try turning off card read DMA in the per-game settings menu.

Confirmed no change.

We then both downgraded to v0.25.2, kept card read DMA off, and are able to connect successfully.

**Comment by RocketRobz** [comment] 2022-07-17 05:54
I suggest finding out which version started causing this issue then.

**Comment by RocketRobz** [comment] 2022-10-22 06:54
Since a multiplayer fix has been implemented some versions ago, I don't see why this issue would persist, so I'll close this.

**Closed by RocketRobz** 2022-10-22 06:54 UTC
Labels: Bug, Retail

**Comment by giovyg20** [comment] 2023-10-20 21:10
still broken for me, tried with different 3ds with everything updated and still gets communication error

**Comment by RocketRobz** [comment] 2023-10-20 21:12
> still broken for me, tried with different 3ds with everything updated and still get communication error

Wait for the next version to release then.

**Comment by giovyg20** [comment] 2023-10-21 00:15
> > still broken for me, tried with different 3ds with everything updated and still get communication error
> 
> Wait for the next version to release then.

thank you (?)
sorry I didn't want to sound annoying or something
