### ISSUE TITLE
Sonic Rush crashing with a garbled background(also happens on 67MHz)

### ISSUE THREAD

**Issue by TheMCNerd2017** [DS-Homebrew/nds-bootstrap#60] opened 2017-02-17 13:12 UTC
While playing Sonic Rush off of the SD card using TWLoader(with the latest unofficial nds-bootstrap), I always seem to experience these weird crashes. They happen completely randomly, and only seem to affect levels with have multiple background layers.

![img_1028](https://cloud.githubusercontent.com/assets/25375242/23066375/4114aecc-f4e8-11e6-8308-0d0608e9ddac.JPG)

As you can see in the image, the game has crashed with the whole top background becoming garbled. You should note that the garbled background also changes extremely fast(like static on a TV). This crash also seem to happen more commonly when playing as Sonic instead of Blaze.

**Comment by Lykie** [comment] 2017-02-17 13:51
https://docs.google.com/spreadsheets/d/1M7MxYQzVhb4604esdvo57a7crSvbGzFIdotLW0bm0Co/edit#gid=0
"Seems to freeze with strange artifacts in the background at random with CPU speed set to 133 MHz, 67 MHz is recommended."

**Comment by TheMCNerd2017** [comment] 2017-02-17 14:15
Yeah, I have it set to 133mhz to get rid of lag in several games. I'll set it to 67mhz and see if that works.

**Comment by TheMCNerd2017** [comment] 2017-02-17 14:34
OK, it didn't work. Even worse crash, with glitch sound effects.

![img_1029](https://cloud.githubusercontent.com/assets/25375242/23069140/4d7c9df8-f4f4-11e6-9120-26401281f58f.JPG)

**Comment by weirdal3333** [comment] 2017-02-18 16:22
Sonic's getting overclocked! But seriously, I have this issue too.

Maybe the physical sonic rush cartridge is different from the rest? 
Has anyone noticed any differences in the config when playing with a PC? (Maybe desmume or no$gba?)

**Comment by ahezard** [comment] 2017-02-19 15:25
Are you using a new3ds or old3ds? Which cluster size have you chosen when you formatted your sd?

I cannot see any explanation apart an issue created by the slow read speed. I played some time to Sonic Rush without problem (with both Sonic and Blaze). I will see if I encounter the issue as well in the future.

I am personally using an old 3ds with a 32GB class 10 sdcard formatted with fat32 and 32kb cluster (cluster size is important)

**Comment by TheMCNerd2017** [comment] 2017-02-19 16:26
I am using a N3DSXL which you can clearly see from the image. I chose 32KB cluster size for my MicroSD card which is formatted as FAT32. Also, my MicroSD card has a V30 rating, and it's a SanDisk.

**Comment by ahezard** [comment] 2018-02-18 22:25
Is this issue still present?

**Comment by Robz8** [comment] 2018-02-19 01:13
Yeah. That issue also happens on a flashcard.
It's caused by TWL clock speed.

**Comment by ahezard** [comment] 2018-06-19 17:09
Can someone retest this with the latest release and confirm if it is fixed with NTR clock speed 67mhz? I never encounter the issue myself. If the issue is only happening with TWL clock speed there is nothing we can do about it.

**Comment by TheMCNerd2017** [comment] 2018-06-19 17:46
You mean with the 9.0-RC2 release?

**Comment by TheMCNerd2017** [comment] 2018-06-19 18:03
Well with the 9.0-RC2 release, the issue seems to be gone when playing with 67MHz selected. However I only played it for about 10 minutes(going through Acts 1&2 of Zone 7).

**Comment by ahezard** [comment] 2018-06-19 18:35
Thanks for the feedback! we can keep this open for a while and then close it if the issue is no more reported.

**Comment by theclashingfritz** [comment] 2018-06-19 19:05
I'll check it again as i experience this alot. Will keep you posted if it still occurs for me.

**Comment by TheMCNerd2017** [comment] 2018-06-19 19:12
OK.

**Comment by theclashingfritz** [comment] 2018-06-20 06:38
Haven't had it happen. Hopefully fixed.

**Comment by ahezard** [comment] 2018-06-21 21:17
I close this for now. If anyone encounter this again please report and it will be reopened

**Comment by hansoljin** [comment] 2021-03-18 04:30
How often are crashes expected? I played this for about half an hour today and experienced no issue. nds-bootstrap 0.37.0, 133mhz, DSi XL w/ Unlaunch

**Comment by homebrewmaster** [comment] 2021-05-09 00:35
Hello sir if you are still having issues use the dpad RESON:I don’t have the exact reson but it could be the pepole who got the data took it out from a ds not 3ds so that one specific part can’t utilize the circle pad as it does not know how but you can by pass that part by using the dpad if it still does not work let me know

**Comment by spellboundtriangle** [comment] 2022-03-02 20:13
Is this still an issue? From what I've read, it seems to be fixed at this point.

**Closed** 2022-03-02 20:24 UTC
Labels: Retail
