### ISSUE TITLE
Select the SAV path

### ISSUE THREAD

**Issue by mercuryisbs** [DS-Homebrew/nds-bootstrap#1360] opened 2022-02-27 21:44 UTC
**Your console:**
Old 3DS, v11.15.0-47

**Launch Method:** SD Card, NDS Bootstrap 0.54.1 with TWiLight Menu++ 24.1.0

**Version used:**
N/A

**Game tested/used/applicable:**
N/A

**Expected Behavior:**
It should be possible to select the SAV path. Want another SAV path for my NDS games, there should be a total of 4 possibilities.

- default
- write save files in the same directory as the game files
- individual directory for all games
- per game an individual SAV path can be selected

**Actual Behavior:**
It is not possible to choose another SAV path.

### Steps to reproduce
1. Open TWiLight Menu++ setting
2. Go to NDS area -> Save Location
3. Point 2 does not exist, there is no separate NDS area for SAV Path

### Other notes

**Comment by Peter0x44** [comment] 2022-02-27 21:50
Pretty sure nds-bootstrap just uses whatever is in nds-bootstrap.ini, so this is actually an issue for TWiLight Menu++.
Though I do remember this being discussed before, I don't think it was agreed it was a worthwhile change.
Previously, TWiLight Menu++ just used the same directory as the nds.
Is there any reason you cannot use `saves`?

**Comment by mercuryisbs** [comment] 2022-02-27 22:09
@Peter0x44 
Hi, thanks for the reply. If the report is not in the right section, you can also move it to TWiLight Menu++.

I play with many different emulators on different platforms and therefore have my own paths for the save files. It would be very helpful if I could select in which path or per game in which path.

**Comment by lifehackerhansol** [comment] 2022-02-27 23:39
Duplicate of https://github.com/DS-Homebrew/TWiLightMenu/issues/1489. Please provide feedback there.

**Closed by lifehackerhansol** 2022-02-27 23:39 UTC
