### ISSUE TITLE
SAGA 3 Crashes at first battle + Black screens on save load

### ISSUE THREAD

**Issue by nameless1** [DS-Homebrew/nds-bootstrap#271] opened 2018-06-30 23:37 UTC
The Fan Translated SAGA 3 Loads and seems to run quite well till you are thrown into the first battle, after you issue all commands and the attack phase is supposed to start the game freezes.
 I'm not sure if this is due to the fan translation or the actual game itself.

 Edit: ack it looks like the compatibility list stats that. Hopefully this can be fixed though, would love to play through SaGa 3.

**Comment by nl255** [comment] 2018-07-03 20:29
Here are xdelta format AP patches for Saga 3 (both for the English translation and the original rom) since the original fix requires running some random .exe file from filetrip.  Unfortunately they do not help with the freezing issue at all.


[saga3-ap.zip](https://github.com/ahezard/nds-bootstrap/files/2160920/saga3-ap.zip)

**Comment by nl255** [comment] 2018-07-07 22:31
After further testing I can confirm that the original untranslated game with just the AP patch applied does the same thing.  Also, if you try to load a saved game it will black screen as soon as you choose "load game".

**Comment by ahezard** [comment] 2019-03-04 23:46
could be linked to #554 that have been fixed. Please retest with the latest nightly.

**Comment by ahezard** [comment] 2019-03-12 22:44
Could be related to the saves patching code, wood contains a specific code regarding save for this game
https://github.com/ahezard/woodrpg_forwarder/blob/e0280c91b21e28443c23f98a171012ef8a301b0c/akloader/arm9/source/patches_sd.cpp

**Comment by ahezard** [comment] 2019-03-18 22:31
The issue is still present with the latest nightly.

**Comment by ahezard** [comment] 2019-05-17 00:03
The issue is still present

**Comment by RocketRobz** [comment] 2019-10-23 04:33
Does this bug persist in v0.26.1?

**Comment by geogolem** [comment] 2020-03-02 03:04
This bug is still present for me today. Im pretty sure I have the latest version of everything possible..

**Comment by geogolem** [comment] 2020-08-11 19:04
issue still stands true today with twilightmenu++ v16.1.0 (and associated NDS boostrap)

**Comment by dhollinger** [comment] 2021-05-05 05:40
Still seeing this issue in NDS Bootstrap 0.39.1 and TM++ v20.1.0

**Comment by Vandalhart** [comment] 2021-05-26 16:41
I grabbed the most recently nightly builds and now the game gets into the prologue a screen or two but the image becomes garbled pixels and a black screen.

**Comment by Vandalhart** [comment] 2021-06-01 10:04
Okay, so after removing the deprecated Twilight updater and grabbing the latest through Universal Updater, I am able to get to the battle, but this last attempt had a white screen when the battle started. Music was playing, but nothing seemed to load after the white screen never transitioned to the battle.

**Comment by denicalis** [comment] 2021-11-29 22:33
NDS 0.51.1 and TM++ 23.1.1 and still happening. Really wish we could get this one solved.

**Comment by geogolem** [comment] 2022-01-16 19:37
still happening when I tested today with https://github.com/DS-Homebrew/TWiLightMenu/releases/tag/v23.4.0

**Comment by RocketRobz** [comment] 2022-02-19 06:05
Both the .ips and cheat versions of the AP-fix give the same issue.
Seems to be an undocumented AP issue at this point.

**Comment by geogolem** [comment] 2023-04-30 14:24
Just wanted to give an update.. I tried this today with the latest twilight menu and nds bootstrap (0.71.1) and I still experienced a problem after inputting all the commands in the first battle. The game didn't freeze like it used to, but it crashed and restarted back to the game title screen... not sure if this is anything different... I didnt try it a second time.. but it happened at the same time it always used to freeze... Just thought I would update since I did try it again.

I didn't really expect anything different, but was hopeful and thought i would give it a try.

**Comment by criddick32** [comment] 2023-05-21 21:01
I used an R4 flashcard with the ds roms on it and got past the first fight with no problem. It seems that it's just the anti piracy check stopping bootstrap. You can get a flashcard on ebay for like 5 bucks so if you want to play then I recommend doing this method instead.

**Comment by Dartz150** [comment] 2023-09-17 12:21
Game is able to get past the battle if DSi mode is forced, but will give a black screen if you try to load a previously saved game.

Tested using nds-bootstrap 1.0.0

**Comment by twocows** [comment] 2024-06-22 19:18
I'm not sure if it's worth tracking in a separate issue because it's probably a similar underlying cause, but I've found that SaGa 2 with the fan TL also crashes almost immediately (about 1-2 minutes of dialog after you create your character). Tested on an O3DSXL and a N2DSXL. Seems to always crash in the exact same spot every time.

If you'd like me to create a separate issue to track it or if more info would be helpful, let me know.

**Comment by ExData7** [comment] 2024-06-24 12:08
> I'm not sure if it's worth tracking in a separate issue because it's probably a similar underlying cause, but I've found that SaGa 2 with the fan TL also crashes almost immediately (about 1-2 minutes of dialog after you create your character). Tested on an O3DSXL and a N2DSXL. Seems to always crash in the exact same spot every time.
> 
> If you'd like me to create a separate issue to track it or if more info would be helpful, let me know.

Are you using the v2.12 patch? If so use the v2.11 patch for SaGa 2. v2.12 used to work with nds bootstrap but I'm not sure what version before or after 1.0 broke compatibility. And v2.12 patch Corrected the header related issues and restored DSi related data to the header but I'm not too sure if that's important for nds bootstrap might have to ask DeadSkullzJr since they made that patch

**Comment by RocketRobz** [comment] 2024-09-18 23:57
According to @ExData7, the red screen crash during the tutorial battle has been fixed on the 200th release, but loading save data causes a black screen crash.

**Closed** 2024-09-26 06:25 UTC
Labels: Bug, Retail, Needs Testing, AP Issue

**Comment by Kenshokram** [comment] 2024-10-04 20:55
Hi! Sorry to post on a closed issue, but I was checking the compatibility list and this game is still listed as crashing on the first battle, but this discussion seems to be more recent than that, and also, if the issue is closed does it mean that it was fixed, or deemed unfixable? (black screen on loading I mean)

Additionally, I see no mention of SaGa 2 on the compatibility list although it was also not working and mentioned on this issue, but I'm not sure if that was deemed an external factor with the different translation patches.

Sorry again if this is the wrong place, and thank you for the amazing software!

**Comment by RocketRobz** [comment] 2024-10-04 20:59
> Hi! Sorry to post on a closed issue, but I was checking the compatibility list and this game is still listed as crashing on the first battle, but this discussion seems to be more recent than that, and also, if the issue is closed does it mean that it was fixed, or deemed unfixable? (black screen on loading I mean)
> 
> Additionally, I see no mention of SaGa 2 on the compatibility list although it was also not working and mentioned on this issue, but I'm not sure if that was deemed an external factor with the different translation patches.
> 
> Sorry again if this is the wrong place, and thank you for the amazing software!

In this case, the issue being closed means the issue is fixed.
Also, the compatibility listings for those games are out of date, and would have to be updated by whoever can edit the list.
