### ISSUE TITLE
Platinum won't connect to pbr on the wii

### ISSUE THREAD

**Issue by KingVulpes** [DS-Homebrew/nds-bootstrap#1532] opened 2023-02-26 19:22 UTC
Whenever I try connecting my Platinum rom through twilight menu to the wii it gives me an error saying "Save data could not be read"
Is there anyway to fix this?

**Comment by RocketRobz** [comment] 2023-02-26 19:41
Duplicate of #415

**Comment by RocketRobz** [comment] 2023-02-26 19:42
There is currently no known fix.

**Closed by RocketRobz** 2023-02-26 19:41 UTC
