### ISSUE TITLE
Assassin's Creed II - Discovery (Europe)

### ISSUE THREAD

**Issue by AngelRG** [DS-Homebrew/nds-bootstrap#1721] opened 2024-07-20 14:31 UTC
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [X] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD Card

### Version used

Latest

### Game tested/used/applicable

Assassin's Creed II - Discovery (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da) (NDSi Enhanced)

### Expected Behavior

Run the game normally

### Actual Behavior

Get Stuck

### Steps to reproduce

Just play the game

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DONORTWLONLY0_NDS_PATH = nand:/title/00030005/484e4b45/content/00000002.app
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 1
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 1
CONSOLE_MODEL = 0
HOTKEY = 284
NDS_PATH = sd:/roms/nds/Assassin's Creed II - Discovery (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da) (NDSi Enhanced).nds
SAV_PATH = sd:/roms/nds/saves/Assassin's Creed II - Discovery (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da) (NDSi Enhanced).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = es
LANGUAGE = -1
REGION = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 5
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Logs

[NDSBTSRP.LOG](https://github.com/user-attachments/files/16321396/NDSBTSRP.LOG)

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment] 2024-07-20 14:53
Game boots fine on my side. Tested in DSi mode and using both Unlaunch and Memory Pit.

1. What's the exact nds-bootstrap are you using? `Latest` doesn't help.
2. Is Unlaunch installed?
3. Do other games have the same issue?

**Comment by AngelRG** [comment] 2024-07-20 15:11
Sorry, I'm new 😅
The exact version is the v1.5.4
Unlaunch is installed
I just play 5 games and that is the only with the issue... I already test another roms and switch to Dsi mode

**Comment by RocketRobz** [comment] 2024-07-20 15:14
> Sorry, I'm new 😅 The exact version is the v1.5.4 Unlaunch is installed I just play 5 games and that is the only with the issue... I already test another roms and switch to Dsi mode

If the nds-bootstrap logo appeared on first launch of the non-booting game, then your ROM might be corrupted.
Please follow the SD setup guide here: https://dsi.cfw.guide/sd-card-setup.html

**Comment by AngelRG** [comment] 2024-07-20 15:15
The game boots

**Comment by AngelRG** [comment] 2024-07-20 15:15
The game boots fine and I play the game, but while I was playing, get stuck in the first level

**Comment by RocketRobz** [comment] 2024-07-20 15:19
> The game boots fine and I play the game, but while I was playing, get stuck in the first level

Haven't gotten that issue in the USA version, though I never tried the first level in the Europe version.
Please try the USA version, and see if you also get stuck there.

**Comment by AngelRG** [comment] 2024-07-20 15:21
In the USA version have the same problem

**Comment by RocketRobz** [comment] 2024-07-20 15:26
> In the USA version have the same problem

Are you sure this is an nds-bootstrap issue then? Because the last time I tried, I got past the first level.

**Comment by AngelRG** [comment] 2024-07-21 02:57
I think.... And the correct way is "The Game Freeze" while playing. Sorry for my poor English.

**Comment by RocketRobz** [comment] 2024-07-21 03:09
> I think.... And the correct way is "The Game Freeze" while playing. Sorry for my poor English.

Please record a video of the issue.

**Comment by AngelRG** [comment] 2024-07-22 00:22
This is the USA version.

https://github.com/user-attachments/assets/e64677b2-0095-45ed-9212-7c8dae4ae7f6

**Comment by RocketRobz** [comment] 2024-09-03 00:56
> This is the USA version.
> 
>  video.mp4

I cannot reproduce this issue. Maybe it got fixed in later versions?

**Closed by RocketRobz** 2024-09-03 00:56 UTC
Labels: Retail, Cannot reproduce
