### ISSUE TITLE
Anonymous Notes 1 save error

### ISSUE THREAD

**Issue by angermanaged** [DS-Homebrew/nds-bootstrap#1380] opened 2022-03-16 11:14 UTC
**Your console: o3DS**

**Launch Method: SD Card**

**Version used: Released**

**Game tested/used/applicable: KVIE 6236A0E1**

**Expected Behavior: normal startup and playability**

**Actual Behavior: an error on startup stating "could not write data. Please turn the power off"**

### Steps to reproduce
1. Get anonymous notes chapter 1 (dsiware)
2. Start up from twighlight menu
3. Get the error

```
### nds-bootstrap.ini
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
LOADING_SCREEN = 1
CONSOLE_MODEL = 2
NDS_PATH = sd:/roms/dsiware/Anonymous Notes 1 - From The Abyss (USA).nds
SAV_PATH = sd:/ROMS/DSIWARE/SAVES/ANONYM~1.PUB
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = 1
DSI_MODE = 1
BOOST_CPU = 1
BOOST_VRAM = 1
DONOR_SDK_VER = 5
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
HOMEBREW_ARG =
CACHE_FAT_TABLE = 0
PRECISE_VOLUME_CONTROL = 0
COLOR_MODE = 0
SOUND_FREQ = 0
GAME_SOFT_RESET = 1
AP_FIX_PATH =
CARD_READ_DMA = 1
EXTENDED_MEMORY = 0
APP_PATH = sd:/ROMS/DSIWARE/ANONYM~3.NDS
PRV_PATH = sd:/ROMS/DSIWARE/SAVES/  
GUI_LANGUAGE = en
REGION = -1
ASYNC_CARD_READ = 0
USE_ROM_REGION = 1
B4DS_MODE = 0
SDNAND = 0
MACRO_MODE = 0
HOTKEY = 284
```

### Logs
```
findModuleParamsOffset:
Module params offset restored: 02004FF4
sdk_version: 05057532

arm9 is not compressed
hi heap end: 02018AAC

old hi heap value: E3A007BE

new hi heap value: E3A007BD

Hi Heap Shrink Sucessfull

cardIrqEnable location : 020172D0

Reset (TWL) patched!
Exit-to-menu patched!
nandTmpJumpFunc location : 0201A5B8

SCFG_EXT location : 0238021C

cardIrqEnable location : 02384918

hookNdsRetailArm7
hookLocation arm7: 023A5538

ERR_NONE
hookLocation arm9: 02FE0020

Device list address: 03800F40
                                                       
                                                                

```

### Other notes
This game worked in the last update or 2 updates ago.

**Comment by lifehackerhansol** [comment] 2022-03-16 19:50
"Release"
Which version is "release"? You can check this in TWiLight Menu++ settings.

**Comment by RocketRobz** [comment] 2022-03-16 20:23
This game boots fine on my side, so you could be on an outdated version.
Cannot reproduce, so closing.

**Comment by angermanaged** [comment] 2022-03-20 03:38
My bad I've been busy for a long time. Im on twighlight menu version 24.2.1

**Comment by angermanaged** [comment] 2022-03-20 03:39
And nds bootstrap ver 0.55.1

**Comment by RocketRobz** [comment] 2022-03-20 03:42
Can you upload the .pub file from the `saves` folder? It's in the same location as the .nds file.

**Comment by RocketRobz** [comment] 2022-03-20 03:59
Ok, I was able to reproduce this with a new save file created.
There seems to be a low chance of it starting though, so keep trying if you keep getting the error.
When it does start, try playing through the game to save data.

**Comment by angermanaged** [comment] 2022-10-11 08:59
I will upload the .pub file here in a bit

**Comment by RocketRobz** [comment] 2023-09-25 21:24
Have not been able to reproduce the issue lately, so I'm sure it's fixed.

**Closed by RocketRobz** 2023-09-25 21:24 UTC
Labels: Bug, Retail
