### ISSUE TITLE
Jam With The Band (Europe) Doesn't Work

### ISSUE THREAD

**Issue by MarkTheFreak** [DS-Homebrew/nds-bootstrap#599] opened 2019-04-12 00:01 UTC
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- []  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- []  Unlaunch+HiyaCFW _[please specify versions of both]_ Unlaunch 1.8 and latest HiyaCFW version

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- []  Release _[0.17.1]_
- []  Nightly _[I believe it is the latest nightly, but TWLMenu++ doesn't tell me]_

### If this issue only affects a certain game, which game is it?

Jam With The Band

### Expected behaviour

The game should get past nds-bootstrap's loading screen.

### Actual behaviour

The Nds-bootstrap loading screen displays an Error! message and freezes on both the latest Release and Nightly of nds-bootstrap.

### Steps to reproduce

1. Launch a European rom of Jam With The Band on TWLMenu++
2. Wait for the ROM to load
3. About 3 quarters into loading the rom, it should display Error!

### Other notes
I believe this might be an issue with the save data, as the game utilises a NAND to store game and save data, like WarioWare DIY.

![IMG20190412095309](https://user-images.githubusercontent.com/34928912/56003443-e33c9d00-5d09-11e9-9aa6-595be1c8540b.jpg)

**Comment by dubbz82** [comment] 2019-04-12 00:36
This was confirmed in discord to NOT be a likely fault of the rom itself either, as it appears to match no-intro's checksums.

**Comment by dubbz82** [comment] 2019-04-12 01:36
Reportedly this game has a NAND based structure similar to Warioware D.I.Y.  I suspect this is probably the main cause of the issue.

**Comment by MasterGamingYT** [comment] 2019-04-12 23:10
@dubbz82 Does the US version work?

**Comment by dubbz82** [comment] 2019-04-13 00:08
US version isn't a thing (at least not under that name...not familiar enough with it to know if it was released under a different name in the US)

**Comment by MarkTheFreak** [comment] 2019-04-13 03:30
There was never a US release of Jam With The Band.
It released in Japan in 2008 iirc and 2010 in Europe.

**Comment by MasterGamingYT** [comment] 2019-04-14 23:23
Then does the japanese version work?

**Comment by ahezard** [comment] 2019-04-15 19:58
I can confirm NAND functions needs to be implemented for this game like for Warioware D.I.Y

**Comment by ahezard** [comment] 2019-04-15 19:59
This is the same issue as #306

**Comment by ahezard** [comment] 2019-05-18 17:03
This game have other issues besides NAND save functions which are now implemented.

**Comment by ahezard** [comment] 2019-05-18 17:07
Jam with the Band now boots, but is unable to load data

**Comment by MasterGamingYT** [comment] 2019-05-18 17:15
ok :)

**Comment by Margen67** [comment] 2019-05-18 17:54
@MasterGamingYT Thanks for your comment. Really adds to the conversation.

**Comment by ahezard** [comment] 2019-05-19 10:03
There is 1 other patch for this game in the wood code : https://github.com/ahezard/woodrpg_forwarder/blob/e0280c91b21e28443c23f98a171012ef8a301b0c/akloader/arm9/source/patches_pr.cpp 
This is a "PatchFlashCardCheck" (AP)
Is there an AP patch for this game?

**Comment by Barawer** [comment] 2019-05-19 10:47
its seems there is an AP patch (From RetroGameFan's Alternative Game Patches v1.8) but even with it i get the load data error.

**Comment by AbnormalPoof** [comment] 2021-07-22 22:39
I assume NAND saves have been implemented since issue #603 is closed, so shouldn't this be closed as well?

**Comment by RocketRobz** [comment] 2021-07-22 23:05
Unfortunately, the game errors, after entering your information.

**Comment by AbnormalPoof** [comment] 2021-07-22 23:06
sad

**Comment by SanicStudios** [comment] 2021-07-31 00:23
Booted the game today and managed to get all the way into the game. Trying to save a custom song triggers the save error and corrupts the save file, making it impossible to continue into the 'Shop Entrance' screen without deleting the save.

**Comment by MarkTheFreak** [comment] 2021-09-06 06:47
I booted up the game on v0.46.1 of NDS-Bootstrap and was only able to input my user information before the game errored out.

Here's the log if it's of any help.
```
findModuleParamsOffset:
Module params offset restored: 02000BBC
sdk_version: 04027539
arm9 is compressed

Switched to NTR mode BIOS
patchCardNds

cardIrqEnable location : 020D1AB4

startOffset : 02080000

cardRead location : 020DDBA0
023F0000

swi12 location : 020007C0

cardPullOut location : 020DDFA8

cardId location : 020DDC90


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 020DD8F0


NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 020DD98C

patchMpuSize: 00000000

Mpu2 init: 020D38F0

reset location : 020D4290

ERR_NONE

cardIrqEnable location : 02383B0C

forwardedRelocStartAddr
02380204
vAddrOfRelocSrc
0238021C
Relocation src: 0238021C
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 0238B5F0
Eeprom read:	0238B5FC
Eeprom page write:	0238B610
Eeprom page prog:	0238B624
Eeprom verify:	0238B638
Eeprom page erase:	0238B648
swiHalt location : 02380694

swi12 location : 0238BA30

swiGetPitchTable location : 02386FE8

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238F780

ERR_NONE
hookLocation arm9: 027E0000

AP-fix found
AP-fix applied
chipID: 80007FC2
```

**Closed** 2022-08-04 03:07 UTC
Labels: Bug, Retail, Major

**Comment by JohnSmith2007** [comment] 2022-09-17 01:53
@RocketRobz  Umm... why is the issue closed if it still hasn't been fixed?

**Comment by RocketRobz** [comment] 2022-09-17 01:54
It's closed because it's already been fixed.
If you're still getting the issue, then please update nds-bootstrap. If the issue persists, then try re-installing.
