### ISSUE TITLE
Another possible bug with NDsi Enhanced Roms

### ISSUE THREAD

**Issue by 39Gambit** [DS-Homebrew/nds-bootstrap#1616] opened 2023-09-01 13:19 UTC
**Your console:** Original 3DS

**Launch Method:** Launched via the SD card, on nds bootstrap version 0.73.1 and 3DS sys version 11.17.0-50U

**Version used:** latest

**Game tested/used/applicable:** Pokemon Black 2

**Save file:** 
[black2.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/12498300/black2.zip)

**Expected Behavior:** Game plays like normal

**Actual Behavior:** Game crashes constantly

### Steps to reproduce
1. Launch the game
2. Play for around 3 minutes
3. Game Crashes

### nds-bootstrap.ini
[nds-bootstrap.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/12498309/nds-bootstrap.zip)

### Other Comments

 There might be another bug with the NDsi Enhanced Roms for DS games being played on a 3DS because no other rom type has this kind of issue.

### Will you be available for future issues and/or replies?
Yes

**Comment by RocketRobz** [comment] 2023-09-01 19:46
Duplicate of #1608

**Closed by RocketRobz** 2023-09-01 19:46 UTC
