### ISSUE TITLE
Tales of Innocence

### ISSUE THREAD

**Issue by Doux91** [DS-Homebrew/nds-bootstrap#932] opened 2020-05-09 21:01 UTC
**Your console:** 3ds
**Launch Method:** Luma 10.1.3 - TWiLight Menu++. v15.0.0 - SD
**Version used:** Release nds-bootstrap v0.35.0.
**Game tested/used/applicable:** Tales of Innocence

**Expected Behavior:** Do not have that frozen scenes
**Actual Behavior:** The game freezes if you don't skip the intro and freezes for 3 or 4 second in most conversations

### Steps to reproduce

You must press A or Start before the intro start and you can play the game, this is not the worst issue, in most conversations the game freezes like 3 or 4 seconds o more, everytime I press A to see the next part but it takes second to see the next dialogue, that makes the game longer it is, the game works pretty well but in that kind of conversation I see the issue

### Other notes
I am not english speaker so I apologize if I said something

**Comment by RocketRobz** [comment] 2020-05-09 21:02
Try turning off heap shrink.

**Comment by Doux91** [comment] 2020-05-09 21:02
> Try turning off heap shrink.
I try everything, in the configuration but nothing helps

**Comment by Doux91** [comment] 2020-05-09 21:04
> Try turning off heap shrink.

I tried everything in the menu but nothing helps, just if you fix the issue it will work like it should be

**Comment by RocketRobz** [comment] 2020-05-09 21:42
Unfortunately, I don't know how to fix this.
@ahezard probably could try, though.

**Comment by Doux91** [comment] 2020-05-09 21:59
> Unfortunately, I don't know how to fix this.
> @ahezard probably could try, though.

jajajaja, that issue makes the game longer cuz I lose minutes in almost every conversations, the game has a clock, in the conversations the clock stops too, so thats why I say the game freezes,  even if you dont fix it or your friend thanks for twilight menu

**Comment by KururinX** [comment] 2021-03-27 17:44
I confirmed the playback of the opening movie at Tales of Innocence. Thank a lot.

Tales Of Innocence (JP)
Twilight Menu : 19.1.1
bootstrap : 0.38.0

**Comment by RocketRobz** [comment] 2022-02-22 03:12
Various improvements have been made since then. Closing.

**Closed by RocketRobz** 2022-02-22 03:12 UTC
