### ISSUE TITLE
I want to play the golden sun: Dark Dawn

### ISSUE THREAD

**Issue by xz685** [DS-Homebrew/nds-bootstrap#1422] opened 2022-07-06 09:40 UTC
**Your console:**new3dsll

**Launch Method:**twilightmenu

**Version used:**v24.1

**Game tested/used/applicable:**Golden Sun: Dark Dawn

**Expected Behavior:**Normal play

**Actual Behavior:**no play,nds bootstrap wrong

### Steps to reproduce
1. open
2. play
3. no play

**Comment by RocketRobz** [comment] 2022-07-06 09:40
Duplicate of #252

**Comment by RocketRobz** [comment] 2022-07-06 09:41
It is currently unknown how to make it boot properly yet.

**Closed by RocketRobz** 2022-07-06 09:40 UTC
