### ISSUE TITLE
Pokémon Tapping DS UNPLAYABLE

### ISSUE THREAD

**Issue by RuneinA** [DS-Homebrew/nds-bootstrap#1460] opened 2022-09-25 18:34 UTC
Your console: New 3DS XL

Launch Method: SD

**Version used:0.64.1

**Game tested/used/applicable:Pokémon Tapping DS JPN

**Expected Behavior:**

**Actual Behavior: The game does not advance after the tutorial, it repeats it ad infinitum. Even with a game already started.
I am using the original keyboard and all the original dumps.

But if you don't want to use the keyboard the game is also unplayable because the touch screen doesn't work.
In addition, the game save in the game in the original cartridge

**Comment by Peter0x44** [comment] 2022-09-25 19:38
I believe this is a duplicate of #1252

**Comment by RuneinA** [comment] 2022-09-25 19:50
but I also comment that the tutorial is infinite, and you cannot advance

**Comment by Kaisaan** [comment] 2022-09-29 05:50
Any additional comments related to #1252 should just go under there. Closing.

**Closed by Kaisaan** 2022-09-29 05:50 UTC
