### ISSUE TITLE
Nino Kuni isuue

### ISSUE THREAD

**Issue by informatica042003** [DS-Homebrew/nds-bootstrap#1427] opened 2022-07-14 13:41 UTC
**Your console:**

**Launch Method:**

**Version used:**

**Game tested/used/applicable:**

**Expected Behavior:**

**Actual Behavior:**

### Steps to reproduce
1. 
2. 
3.

**Comment by lifehackerhansol** [comment] 2022-07-14 14:59
Duplicate of #1426.

**Closed by lifehackerhansol** 2022-07-14 14:59 UTC
