### ISSUE TITLE
Pokemon SoulSilver goes into red screen with dots when launching

### ISSUE THREAD

**Issue by HarbingerTJ** [DS-Homebrew/nds-bootstrap#1469] opened 2022-10-12 07:35 UTC
**New Nintendo 3DS:**

**SD Card, either Home Menu Forwarder of Twilightmenu**

**Release 0.65.1:**

**Pokémon Soulsilver EUR ROM (Spanish):**

**Game should've started properly after launching either the forwarder or via the twilightmenu UI:**

**As soon as the game is launched it instantly goes into a red screen with white dots**

### Steps to reproduce
1.Launch game
2. 
3. 

I can't share any logs ATM as its 4am and I downgraded back to 0.64.1, which got the game working again, I'll try to replicate this issue as soon as i can to share logs if needed

**Comment by RocketRobz** [comment] 2022-10-12 07:47
HeartGold (which should have minimal difference) still works fine on my side. Try updating back to v0.65.1. If the issue occurs again, then delete the `patchOffsetCache` folder in `sd:/_nds/nds-bootstrap/`.

**Comment by WALLE1Doctor1Who** [comment] 2022-10-15 22:03
I'm having the same issue, only with Mario vs Donkey Kong Mini-land Mayhem and it occurs if you try to start a level. So far, at the very least level 2-4 is affected. I even tried to do a clean install of TwilightMenu++ (and subsequently nds-bootstrap) and the issue still persists. I can't find the log file, so I'll just include a link to an archive file containing the contents of the SD card when the issue occurred [here](https://drive.google.com/file/d/1kp9H05_y8nVxPJM1p-rMChYii9Qaqb4r/view?usp=sharing).

**Comment by RocketRobz** [comment] 2022-10-15 22:12
@WALLE1Doctor1Who The link contained the ROM, which should not be uploaded here.

The log is located on the SD root, and is called `NDSBTSRP.LOG`. If you don't see it, then turn on `Logging` in TWLMenu++ Settings, and try again.

Also, a possible issue could be that the game is trying to allocate more heap than what's actually available.
Are you using a DSi or 3DS? Try changing `Run in` to `DS mode` to fix the issue.

**Comment by RocketRobz** [comment] 2022-11-01 04:13
Please check if the bug is fixed in v0.66.0.

**Comment by WALLE1Doctor1Who** [comment] 2022-11-06 00:33
Sorry about that, I had accidentally forgot to delete it before creating the archive. Either way, the issue is still present, but instead of dots the red screen now shows an error message and some data while also giving me the option to dump the contents of RAM. I'm not sure if I'm allowed to post the RAM dump here but I do have it if you need/want it. Either way, here is the log and a screenshot (since it also allowed me to do that).

[MVSDK Error log.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/9944942/MVSDK.Error.log.LOG)

![MVSDK Error Screenshot](https://user-images.githubusercontent.com/48142986/200148577-1d56a8ee-3934-4fa5-9689-a922e2ec38c9.png)

**Comment by RocketRobz** [comment] 2022-11-06 00:36
> Sorry about that, I had accidentally forgot to delete it before creating the archive. Either way, the issue is still present, but instead of dots the red screen now shows an error message and some data while also giving me the option to dump the contents of RAM. I'm not sure if I'm allowed to post the RAM dump here but I do have it if you need/want it. Either way, here is the log and a screenshot (since it also allowed me to do that).
> 
> [MVSDK Error log.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/9944942/MVSDK.Error.log.LOG)
> 
> ![MVSDK Error Screenshot](https://user-images.githubusercontent.com/48142986/200148577-1d56a8ee-3934-4fa5-9689-a922e2ec38c9.png)
> 
> Edit: I should mention that I had accidentally turned on nds-bootstrap's debug when turning on the log. I will be disabling it and the game was not working when it was off, so that doesn't affect anything. I'm just saying this just in case.

Does DS mode fix the issue?

**Comment by WALLE1Doctor1Who** [comment] 2022-11-06 00:41
Yes. It managed to load a level and I was able to complete it seemingly without issue.

**Comment by RocketRobz** [comment] 2023-06-21 03:08
Closing, due to no response from OP, as well as no recent reports of the issue from other users.

**Closed by RocketRobz** 2023-06-21 03:08 UTC
Labels: Bug, Retail, DSi Mode
