### ISSUE TITLE
Sonic Rush randomly freeze

### ISSUE THREAD

**Issue by TimTH98** [DS-Homebrew/nds-bootstrap#1029] opened 2020-10-30 12:59 UTC
**Your console:** Old3DS
**Launch Method:** Luma 10.2 TWL 16.4.0
**Version used:** Release 0.35.1
**Game tested/used/applicable:** Sonic Rush

**Actual Behavior:** The game has crashed with the whole top or bottom background becoming garbled. You should note that the garbled background also changes extremely fast(like static on a TV). CPU speed set to 67 MHz. I'm using an old 3ds with a 32GB class 10 sdcard formatted with fat32 and 32kb cluster.

### Steps to reproduce

It happens randomly on any levels. 

![image](https://user-images.githubusercontent.com/18901396/97707392-48acd600-1ac8-11eb-9926-a392fc8af3c3.png)
![image](https://user-images.githubusercontent.com/18901396/97707413-4d718a00-1ac8-11eb-9a95-28a60b1d2d4e.png)

**Comment by RocketRobz** [comment] 2020-11-15 00:55
Duplicate of https://github.com/DS-Homebrew/nds-bootstrap/issues/60

**Closed by RocketRobz** 2020-11-15 00:55 UTC
