### ISSUE TITLE
Mario & luigi bowser's inside story file select menu not registering buttons

### ISSUE THREAD

**Issue by MegaloDawn** [DS-Homebrew/nds-bootstrap#1522] opened 2023-02-07 21:43 UTC
NDS bootstrap ver. 0.69.0
no expansion pak

When the TWL update came, The first game I've tried was Mario & Luigi bowser's inside story and before the main menu was not showing but it did but came to the issue when going to select a file, The buttons did not register and no my buttons are not at fault because I can access the NDS bootstrap menu with the combo and partners in time a game that used to not work works perfectly and could select my file for that game so that's it

**Comment by RocketRobz** [comment] 2023-02-07 21:44
The buttons are registered on my side.
What region of the ROM are you using?

**Comment by RocketRobz** [comment] 2023-02-07 21:44
Also, please upload the log file, as said by the issue template.

**Comment by EpicDoodleboy2** [comment] 2023-02-07 21:51
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/10679690/NDSBTSRP.LOG)

Its a European rom

**Comment by RocketRobz** [comment] 2023-02-07 21:53
I use the USA ROM, so I guess the European ROM functions differently.
Try the USA ROM instead.

**Comment by EpicDoodleboy2** [comment] 2023-02-07 21:54
> I use the USA ROM, so I guess the European ROM functions differently. Try the USA ROM instead.

Ok

**Comment by EpicDoodleboy2** [comment] 2023-02-07 21:58
> I use the USA ROM, so I guess the European ROM functions differently. Try the USA ROM instead.

still not working with a USA rom

**Comment by RocketRobz** [comment] 2023-02-07 22:00
Try re-installing TWiLight Menu++ then:
https://wiki.ds-homebrew.com/twilightmenu/uninstalling-ds
https://wiki.ds-homebrew.com/twilightmenu/installing-flashcard

If the issue persists, then idk why this issue is occurring.

**Comment by EpicDoodleboy2** [comment] 2023-02-07 22:11
> Try re-installing TWiLight Menu++ then: https://wiki.ds-homebrew.com/twilightmenu/uninstalling-ds https://wiki.ds-homebrew.com/twilightmenu/installing-flashcard
> 
> If the issue persists, then idk why this issue is occurring.

Well... it didn't work

**Comment by EpicDoodleboy2** [comment] 2023-02-07 22:11
> Try re-installing TWiLight Menu++ then: https://wiki.ds-homebrew.com/twilightmenu/uninstalling-ds https://wiki.ds-homebrew.com/twilightmenu/installing-flashcard
> 
> If the issue persists, then idk why this issue is occurring.

should I post a ram dump

**Comment by RocketRobz** [comment] 2023-02-07 22:14
> should I post a ram dump

No. In the RAM viewer, go to offset 023DE000, and post a photo of the RAM viewer screen.

**Comment by EpicDoodleboy2** [comment] 2023-02-07 22:21
> > should I post a ram dump
> 
> No. In the RAM viewer, go to offset 023DE000, and post a photo of the RAM viewer screen.
![20230207_221916](https://user-images.githubusercontent.com/111697934/217380021-fc2eed05-318b-48f7-a599-dbd5db541b14.jpg)

**Comment by EpicDoodleboy2** [comment] 2023-02-07 22:23
I'm going to be inactive soon due to time

**Comment by RocketRobz** [comment] 2023-02-07 22:24
Hmm, ok. It seems the game has overwritten the cheat engine, which allows for the AP-patch to work.
Wait for a fix, ig.

**Comment by EpicDoodleboy2** [comment] 2023-02-07 22:24
thx

**Comment by RocketRobz** [comment] 2023-09-25 20:55
Has been (or should be) fixed some versions ago.

**Comment by Searinox** [comment] 2024-09-10 19:21
This was never explicitly confirmed as fixed was it? Running latest version with NTR-CLJE-USA and having the issue. The title screen confirms and the water effect registers stylus inputs but the File Select menu registers no inputs, button or touch.

**Comment by RocketRobz** [comment] 2024-09-10 19:28
> This was never explicitly confirmed as fixed was it? Running latest version with NTR-CLJE-USA and having the issue. The title screen confirms and the water effect registers stylus inputs but the File Select menu registers no inputs, button or touch.

The issue has been fixed for a while. Are you using TWLMenu++ on your flashcard?

**Comment by Searinox** [comment] 2024-09-10 19:43
Not using a flashcard. New3DS with version 27.7.0 TWLMenu++ and nds-bootstrap 1.6.2. Tried deleting CLJE-CE77.bin from patchOffsetCache folder to no avail. All ROM settings set to Defalt. Tried disabling cache, async etc., setting DS mode explicitly, still no dice.

**Comment by RocketRobz** [comment] 2024-09-10 19:44
> Not using a flashcard. New3DS with version 27.7.0 TWLMenu++ and nds-bootstrap 1.6.2. Tried deleting CLJE-CE77.bin from patchOffsetCache folder to no avail. All ROM settings set to Default. Tried disabling cache, async etc., setting DS mode explicitly, still no dice.

Are you using a modified ROM/ROM hack/translated ROM then?

**Comment by Searinox** [comment] 2024-09-10 19:49
No, didn't touch it. The same ROM file works on 2 flashcarts(R4 clone and SCDS One).

**Comment by RocketRobz** [comment] 2024-09-10 20:12
> No, didn't touch it. The same ROM file works on 2 flashcarts(R4 clone and SCDS One).

Just tried it on my DSi, and I'm getting the same issue now. It seems the WiFi fixes I made has broken cheat support, as the AP-fix is a cheat code.
Try downgrading to v1.5.5.

**Comment by RocketRobz** [comment] 2024-09-10 20:33
Issue was not caused by the WiFi fixes, and will be fixed in the next version.

**Closed** 2024-09-10 20:33 UTC
Labels: Bug, Retail, B4DS

**Comment by Searinox** [comment] 2024-09-10 20:40
Confirmed working on nightly d0a240a.
