### ISSUE TITLE
Glitchy brushstroke behavior in Okamiden

### ISSUE THREAD

**Issue by wad11656** [DS-Homebrew/nds-bootstrap#920] opened 2020-04-26 02:02 UTC
**Your console:** 
Old 3DS NTSC-U

**Launch Method:** 
TWiLight Menu++ 14.2.0

**Version used:** 
nds-bootstrap Release 0.34

**Game tested/used/applicable:** 
Okamiden (USA) (Game ID: BOOE)

**Expected Behavior:** 
Brush stroke should not automatically sporadically release while your stylus is pressed down
![IMG_5859](https://user-images.githubusercontent.com/16929664/80295350-50617b80-872f-11ea-97fd-a989e105481d.jpg)
![IMG_5860](https://user-images.githubusercontent.com/16929664/80295351-50fa1200-872f-11ea-91fc-dbedb65f3e44.jpg)

**Actual Behavior:** 
Brush stroke automatically & sporadically releases on touch screen while stylus is held down
![IMG_5857](https://user-images.githubusercontent.com/16929664/80295370-65d6a580-872f-11ea-905f-51f6cd758825.jpg)
![IMG_5855](https://user-images.githubusercontent.com/16929664/80295371-666f3c00-872f-11ea-81dc-4985867cf608.jpg)
![IMG_5856](https://user-images.githubusercontent.com/16929664/80295372-666f3c00-872f-11ea-8131-7d9ebe398f3d.jpg)

### Steps to reproduce 
Run Okamiden (USA) with default TWiLight Menu++ settings

### Other notes
Bug confirmed also on EUR and JAP versions (GBAtemp thread):
https://gbatemp.net/threads/ds-i-3ds-twilight-menu-gui-for-ds-i-games-and-ds-i-menu-replacement.472200/page-536#post-9030127

**Comment by SleepyLark** [comment] 2020-04-26 02:07
Were the first images taken from the actual cartridge or a flashcart?

**Comment by wad11656** [comment] 2020-04-26 02:08
1st images (the working ones) were running on my R4 flashcart dualbooted in YsMenu firmware

**Comment by raphaelalmeidamartins** [comment] 2020-04-26 12:51
Hi, I'm having the same issue with my New 3DS. Also running the game with this version of Twilight Menu. My console is New 3DS XL and I have tried both american and european ROMs.

**Comment by oneup03** [comment] 2020-04-27 20:23
I'm also having this issue on New 3DSXL, Luma 3DS, TwilightLaunchMenu, nds-bootstrap Ver. 5b975395.

**Comment by SleepyLark** [comment] 2020-04-29 18:17
Tested it on DSi on v0.34.0 and I didn't seem to have any problems with the stylus
![20200429_120827](https://user-images.githubusercontent.com/37351525/80631304-c35e4100-8a12-11ea-90b2-ea7c52cc7892.jpg)
![20200429_120851](https://user-images.githubusercontent.com/37351525/80631321-c9ecb880-8a12-11ea-8751-d2186c835e8a.jpg)
![20200429_120923](https://user-images.githubusercontent.com/37351525/80631352-d07b3000-8a12-11ea-9649-5c2d4d05f3f3.jpg)

Unless someone says otherwise, I think this may only effect the 3DS

**Comment by TheBadger77** [comment] 2020-05-01 23:54
Hi, I am having this same issue on the New 2DS XL using Luma and Twilight Menu++. Looks like its only effecting 3DS models.

**Comment by ILynS** [comment] 2020-05-16 23:48
I run with the same issue it kinda makes running the game hard I try today using the updator app to make sure I have the last version of everything but the big still persist

I use a eu rom version of the game
My twilight launcher is (release version):
V15.1.0

new-bootstrap is (release version):
V0.35.1
 
Full name of my rom of okamiden is:
5605 - Ookami Den (Europe).nds
SDK ver: 5 (TWLSDK)  TID: BOOP

The picture are accurate to my issue as well I notice the touch input act weird in this game for some reason some times the touch screen stay following your input a the other second it stop to follow it than again 

That how I can most accurate tell the problem I also run the rom via drastic on my phone a the issue isn't on there every thing works as intended on drastic emulator on phone so it isn't a issue on it rom

But yeah In short seems input ok the touch screen is reacting wrong not keeping track of your movement fully 

I can do some test or if you like me to try soemthing let me know as I really like to play the game 

I also already try run ing the nightly last version as well but the same issue persist

**Comment by Drazini** [comment] 2020-08-15 02:52
I have this issue as well, although interestingly I believe that when I was using a previous version (released around 2018 I think) of nds-bootstrap i didnt have this issue.

**Comment by Rokkubro** [comment] 2020-08-25 15:59
Should be fixed in #1002 , I've attached a nightly build with the fix applied for testing.
[nds-bootstrap-nightly.zip](https://github.com/ahezard/nds-bootstrap/files/5124908/nds-bootstrap-nightly.zip)

**Comment by TheBadger77** [comment] 2020-08-26 07:23
I have just tested with this new nightly build and was able to consistently draw using this touch screen. Touch input appears to be responding as expected. Thank you very much for you assistance with this issue!

**Comment by ChainSwordCS** [comment] 2021-03-26 16:53
I'm on the latest nightly build, and I am having this issue again. New 3DS.

**Comment by Rokkubro** [comment] 2021-04-13 12:51
> 
> 
> I'm on the latest nightly build, and I am having this issue again. New 3DS.

I cannot reproduce this issue on an N3DS with release 0.38 or the latest nightly(currently 86c4b748). Could you confirm you are still having the issue @ChainSwordCS ?

**Comment by ChainSwordCS** [comment] 2021-04-13 16:36
I'm on mobile so bear with me. I'm on nds-bootstrap version a31f6d4b right now, updated from a Universal-Updater script. That might be my issue...

**Comment by ChainSwordCS** [comment] 2021-04-13 17:18
For some reason I was kinda stuck on Universal-Updater 2.3.0...

Yeah on nightly 86c4b74 this issue is fixed.

**Comment by Kaisaan** [comment] 2022-02-19 05:51
Closing.

**Closed by Kaisaan** 2022-02-19 05:51 UTC
Labels: Bug
