### ISSUE TITLE
Pokemon - Heart Gold + Soul Silver crashing after opening the pokegear

### ISSUE THREAD

**Issue by WhoCloggedTheFunkinToilet** [DS-Homebrew/nds-bootstrap#1480] opened 2022-10-24 00:18 UTC
**Your console:** 2DS XL running the latest version of Twilightmenu++ and the nds bootstrap

**Launch Method:** Launched through SD. It is not locked.

**Version used:** Release. v25.4.0. 

**Game tested/used/applicable:** IPKE/Pokemon Heart Gold. EUR version

**Expected Behavior:** The pokegear menu would open up.

**Actual Behavior:** The game stays at a black screen, and only the music can be heard. Sometimes its a red screen with the music being paused. this makes the game impossible to beat because at certain points people will call you and it forces you to accept them

### Steps to reproduce
1. Open pokegear
2. 
3. 

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
NDS_PATH = sd:/Pokemon - HeartGold Version.nds
SAV_PATH = sd:/saves/Pokemon - HeartGold Version.sav8
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = 1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 0
FORCE_SLEEP_PATCH = 0
GAME_SOFT_RESET = 1
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
PRECISE_VOLUME_CONTROL = 0
SOUND_FREQ = 1
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
HOMEBREW_ARG =
DONOR2_NDS_PATH = sd:/0177 - Sonic Rush.nds
MACRO_MODE = 0
USE_ROM_REGION = 1
B4DS_MODE = 0
SDNAND = 0
HOTKEY = 601
GUI_LANGUAGE = en
REGION = -1
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
```

### Logs
```
findModuleParamsOffset:
Module params offset restored: 02000BBC
sdk_version: 04027533
arm9 is compressed

Switched to NTR mode BIOS
AP-fix found
patchCardNds

cardIrqEnable location : 020D11D4

startOffset : 02000000

cardRead location : 020DD570
027B0000

swi12 location : 0200072A

cardPullOut location : 020DDAD0

cardId location : 020DD660


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 020DD2C0


NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 020DD35C

Mpu start: 02000ADC

Mpu data: 02000B70

Mpu init: 020D3190

Mpu data alt: 020D2ABC

Mpu start 2: 02000AE4

Mpu data 2: 02000B74

Mpu init 2: 020D3198

reset location : 020D3B84

waitCpuCycles location : 020D3AA8

ERR_NONE

Sleep location : 0238A314

cardIrqEnable location : 02380B80

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 0238026C
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 02388730
Eeprom read:	0238873C
Eeprom page write:	02388750
Eeprom page prog:	02388764
Eeprom verify:	02388778
Eeprom page erase:	02388788
swi12 location : 02388B70

swiGetPitchTable location : 02383FCC

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238ECF4

ERR_NONE
hookLocation arm9: 027E0000

AP-fix applied
Overlays cached to a file
chipID: E0017FC2                                                           
```

### Other notes
I tried this on different regional versions AND soul silver. Its the same in all of them.

**Comment by RocketRobz** [comment] 2022-10-24 01:00
The bug should hopefully be fixed in the next version.

**Comment by RocketRobz** [comment] 2022-11-01 04:12
Please check if the bug is fixed in v0.66.0.

**Comment by WhoCloggedTheFunkinToilet** [comment] 2022-11-05 15:12
Sorry Im late to replying. Ill check in a few hours when I get home

**Comment by fail7467** [comment] 2022-11-11 01:45
Hello, I'm having the same problem as the original poster and I'm on the latest version (v0.66.0). I have similar specs as them, but I can provide my logs and screenshots if needed.

**Comment by RocketRobz** [comment] 2022-11-11 01:56
> Hello, I'm having the same problem as the original poster and I'm on the latest version (v0.66.0). I have similar specs as them, but I can provide my logs and screenshots if needed.

Are you sure you're on v0.66.0? It seems to have fixed the crash on my side (though I've never checked on the version known to have the crash).
Please check TWLMenu++ Settings to verify that you're on the latest.

If TWLMenu++ Settings shows v0.66.0, and the crash still occurs, then it may be caused by using either a ROM hack or randomized ROM. If you are using either one, then you'll need to manually AP-patch the clean ROM using DS-Scene ROM Tool, before applying either the ROM hack patch or using the randomizer tool.

**Comment by fail7467** [comment] 2022-11-11 02:50
![20221110_214250-min](https://user-images.githubusercontent.com/80129827/201252073-9aa0aeeb-f121-46b1-803d-1a7dea5437ed.jpg)
Yeah, just double checked again to make sure I am on v0.66.0, and I'm also not playing on a ROM hack or randomized ROM. I've only tried Soul Silver, but I've tried 3 different versions to make sure it wasn't the ROM.

**Comment by RocketRobz** [comment] 2022-11-11 02:55
Try downgrading nds-bootstrap to v0.64.1: https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v0.64.1

**Comment by fail7467** [comment] 2022-11-11 03:38
Thanks for the suggestion, however it is still crashing after the downgrade.

**Comment by RocketRobz** [comment] 2022-11-11 03:40
> Thanks for the suggestion, however it is still crashing after the downgrade.

Then either cheats are enabled, or somehow the issue has gone unnoticed for a while.
Either way, please update back to the latest.

**Comment by kalte-herz** [comment] 2023-01-24 02:58
I'm having the same issue. I just went through and checked that all cheats were off, and I updated to the most recent version, but it's still happening. It didn't seem to be a couple of days ago, as I'd used the PokeGear to check the radio station and it didn't crash, but it does now.

I am running in DS mode if that affects anything

**Comment by aelita01** [comment] 2023-02-06 15:40
Hi, I too had problems with the pokegear on soulsilver (ITALY) or that it crushes as soon as a call starts and most likely there is one of the cheats that doesn't work properly and sends problems to the card but by doing several tests I discovered (only on Rom Italy version) that gives problems with the Pokémon that you receive via pokemarket and the display of eggs and that you have to put the cheats before activating the game (I mean right at the beginning of the story).  At the moment the cheats that don't give problems (for the ones I tried and that served me) are Max money, coins, bypass code, 100% catch, max all items, specific Pokémon level, specific wild Pokémon and play as Pokemon , object, trainer, etc.  I haven't been able to try the others but I will most likely unlock them after finishing the story so as not to have problems moving forward.  I have NDS.bootstrap version 0.69 for those interested.  Ps: if you receive Pokémon by mail with WiFi codes they work fine!

**Comment by gusbronk** [comment] 2023-04-15 03:36
I tested a save with the same symptoms in serveral emulators and they all exhibited the same behavior as NDS-bootstrap/twlmenu. I used cheats to give the event pokemon, I think this was the cause and it has nothing to do with NDS-bootstrap.

**Comment by ForgottFoxxo** [comment] 2023-06-03 08:45
Having same problem as above, used some cheats, specifically the even pokemon ones, Max/unlimited BP and palace points, as well as used the 16x exp one.
Cutting to the red screen when opening the poketech, as well as having a pinked out map when using Fly

**Comment by RocketRobz** [comment] 2023-06-03 08:55
Yeah, I'm pretty sure the cheats have been the issue all along, as it has corrupted the save file, which in turn, causes the crashing.

That said, I wonder how the save corruption can be fixed without starting over or having a backup.

**Closed by RocketRobz** 2023-06-03 08:55 UTC

**Comment by Masamune3210** [comment] 2023-06-04 13:51
Probably the best way would be to back up the corrupted save, make a dummy save and get past all the intro stuff and then back that up as well, and then using pkhex to transplant everything from the corrupted save over to the dummy save.

**Comment by nilchameleons** [comment] 2024-04-01 20:20
I can confirm that this issue no longer occurs with a clean version of the rom. Unfortunately every English-language rom site I could find hosts the same pre-patched copy of this game in Japanese; you'll have better luck searching google for ニンテンドーds rom ダウンロード

You can verify your .nds file is unpatched by checking the file's MD5 hash (plenty of free utilities to do this available on Google).
- Patched file (will crash nds-bootstrap) MD5 (Soul Silver JP): A1211B2D44E551197712177E3D50B491
- **Clean file MD5 (Soul Silver JP): 7148DBB7328D535F1164F787C4156BDE**
