### ISSUE TITLE
The roms don't work when I connect the ds download from other ds

### ISSUE THREAD

**Issue by Ashton845** [DS-Homebrew/nds-bootstrap#1032] opened 2020-11-04 17:48 UTC
Hi. Look I have a problem and it is that when I connect in roms games and use the ds download of my other friends it connects but the signal goes suddenly and says error and the funny thing is that I play like bomberman ds or tetris they grab it but games like cod, mario kart, mario party, etc. The signal goes off and sounds like this all the time and I wanted to know if there is a solution for this (and if I did not comply with some of your rules then I apologize because this is the first time I use github and I am Spanish).

**Comment by RocketRobz** [comment] 2020-11-04 17:56
Duplicate of #553 

It'll be fixed in the future.

**Closed by RocketRobz** 2020-11-04 17:56 UTC
