### ISSUE TITLE
Saga 3  (english translation patched) crash during game play.

### ISSUE THREAD

**Issue by tomudo** [DS-Homebrew/nds-bootstrap#1692] opened 2024-04-15 14:02 UTC
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [X] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD card

### Version used

v27.0.0

### Game tested/used/applicable

Saga 3  (english translation patched)

### Expected Behavior

Run without crash

### Actual Behavior

Crash during game play. For saga 3, crash during first battle. 

### Steps to reproduce

Run game to same crash point.

### nds-bootstrap.ini

```
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = 0
PRECISE_VOLUME_CONTROL = 1
SDNAND = 1
MACRO_MODE = 0
SOUND_FREQ = 1
CONSOLE_MODEL = 0
HOTKEY = 284
NDS_PATH = sd:/roms/NDS/SaGa 3 - Champions of Time and Space - Shadow or Light (Japan) [T-En by Cain & Easton West v2.0.830 Beta] [n].nds
SAV_PATH = sd:/roms/NDS/saves/SaGa 3 - Champions of Time and Space - Shadow or Light (Japan) [T-En by Cain & Easton West v2.0.830 Beta] [n].sav
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = 1
REGION = 1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
HOMEBREW_ARG =
APP_PATH = sd:/ROMS/DSIWARE/DRAGON~2.NDS
PRV_PATH = sd:/ROMS/DSIWARE/SAVES/
GAME_SOFT_RESET = 1
DONORTWLONLY0_NDS_PATH = nand:/title/00030005/484e4b4a/content/00000002.app
SLEEP_MODE = 1

```

### Logs

```
Loading the NDS file...
Header CRC is valid!
Module params offset: 02000BA4
sdk_version: 05057530
arm9 is not compressed
Secure area already decrypted
Switched to NTR mode BIOS
AP-fix found
patchCardNds

[SDK 5]

cardIrqEnable location : 020128A4

startOffset : 02000000

Mpu start: 02000AA4

Mpu data: 02000B38

Mpu init: 02013B98

Mpu change: 020138E0

waitSysCycles location : 020144B4

cardRead location : 0201B7E4
03700000

swi12 location : 02000718

cardPullOut location : 0201BC08

cardId location : 0201B6D0


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 0201B920


NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 0201B984

reset location : 0201452C

ERR_NONE

Sleep location : 0238C4E0

cardIrqEnable location : 02384140

Relocation src: 02380394

Arm7 (patch v5)
JumpTableFunc: 0238F6E8
card id:	0238F6D0
card read:	0238F6E0
Eeprom read:	0238F6F4
Eeprom page write:	0238F70C
Eeprom page prog:	0238F724
Eeprom verify:	0238F73C
Eeprom page erase:	0238F750
swi12 location : 023836E0

swiGetPitchTable location : 023836F4

ERR_NONE

Card patch successful

hookNdsRetailArm7
hookLocation arm7: 02391698

Cheats found and applied
ERR_NONE
hookLocation arm9: 027E0000

AP-fix applied
chipID: 80007FC2

```

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment] 2024-04-15 20:37
Duplicate of #271

**Closed by RocketRobz** 2024-04-15 20:37 UTC
