### ISSUE TITLE
[enhancement] Multiple rows in 3DS theme

### ISSUE THREAD

**Issue by DraconicNEO** [DS-Homebrew/nds-bootstrap#1195] opened 2021-06-27 23:24 UTC
I think it would be a good feature to have the ability to select between 1 to 5 rows on the 3DS theme. This could improve navigation because being able to have more icons on screen would reduce the amount of scrolling, especially for large amounts of games and/or apps.

**Comment by Epicpkmn11** [comment] 2021-06-28 00:38
I think this is a duplicate of DS-Homebrew/TWiLightMenu#749, even if it weren't this would be a TWiLight Menu++ issue not an nds-bootstrap one fyi.

TWiLight Menu++ is the menu, nds-bootstrap is what runs DS games.

**Closed by Epicpkmn11** 2021-06-28 00:38 UTC

**Comment by DraconicNEO** [comment] 2021-06-29 22:39
> I think this is a duplicate of [DS-Homebrew/TWiLightMenu#749](https://github.com/DS-Homebrew/TWiLightMenu/issues/749), even if it weren't this would be a TWiLight Menu++ issue not an nds-bootstrap one fyi.
> 
> TWiLight Menu++ is the menu, nds-bootstrap is what runs DS games.

Oops, sorry I posted in the wrong category.
