### ISSUE TITLE
Gen 4 Pokemon connection to Battle Revolution failing to get past "Found Wii"

### ISSUE THREAD

**Issue by SoulBlast35** [DS-Homebrew/nds-bootstrap#1208] opened 2021-07-13 21:50 UTC
**Your console:** Old 3DS
**Launch Method:** Launched via SD Card through Twilight Menu
**Version used:** Release
**Game tested/used/applicable:** Pokemon HeartGold MD5: DFE6DDB649C40B73DD45370624BDD822 Title ID: IPKE

**Expected Behavior:** Game should have gone from blue screen of Wii connection screen to Pokemon Battle Revolution's logo
**Actual Behavior:** Game constantly flashes to a white fadeout and back to the blue screen of the Wii connection screen

### Steps to reproduce

Start up DS Battle Mode in PBR, and have HeartGold connect via "Connect to Wii". Upon progressing to the Battle Ready screen after selecting a Colosseum (which is where the PBR logo would appear on the DS Screen), this bug will occur and it will immediately lose connection to the Wii and constantly flash to white screen and back until exiting to the Home Menu.

[nds-bootstrap.ini.txt](https://github.com/DS-Homebrew/nds-bootstrap/files/6812183/nds-bootstrap.ini.txt)

### Logs

```findModuleParamsOffset:
Module params offset found: 02004B84
sdk_version: 03027531
arm9 is not compressed

Switched to NTR mode BIOS
relocate_ce9
firstCardLocation 023F0000 : 02780000

armReadCardLocation 023F00F0 : 02780000

thumbReadCardLocation 023F0110 : 02780000

armReadCardDmaLocation 023F0140 : 02780000

armReadSlot2Location 023F0164 : 02780000

armSetDmaCardLocation 023F0194 : 02780000

thumbReadCardDmaLocation 023F01C0 : 02780000

thumbSetDmaCardLocation 023F01E0 : 02780000

armReadNandLocation 023F0204 : 02780000

thumbReadNandLocation 023F0228 : 02780000

armWriteNandLocation 023F0240 : 02780000

thumbWriteNandLocation 023F0260 : 02780000

armIrqEnableLocation 023F0290 : 02780000

thumbIrqEnableLocation 023F02B0 : 02780000

pdashReadLocation 023F02DC : 02780000

thumbReadSlot2Location 023F0300 : 02780000

ipcSyncHandlerLocation 023F0368 : 02780000

resetLocation 023F0390 : 02780000

globalCardLocation 023F1498 : 02780000

 ce9->patches 023F0034

patchCardNds

findCardIrqEnableOffset:
irq enable not found
irq enable SDK 4 found

cardIrqEnable location : 02007AC8

startOffset : 02004000

findCardReadEndOffsetThumb:
ARM9 Card read end thumb not found

findCardReadEndOffsetType0:
ARM9 Card read end (type 0) elaborate not found
ARM9 Card read end (type 0) short not found

findCardReadEndOffsetType1:
ARM9 Card read end alt (type 1) found: 0200DC90

findCardReadStartOffsetThumb:
ARM9 Card read start thumb not found
ARM9 Card read start thumb alt not found

findCardReadStartOffsetType1:
ARM9 Card read start alt 2 (type 1) found

cardRead location : 0200DBB0
023F0000

findSwi12Offset:
swi 0x12 call not found

swi12 location : 00000000

findCardPullOutOffset:
Card pull out handler not found
Card pull out handler SDK 4 found

cardPullOut location : 0200E07C

findCardIdEndOffset:
Card ID end found: 0200DCEC

findCardIdStartOffset:
Card ID start not found
Card ID start alt 1 found

cardId location : 0200DC98


patchCardSetDma
findCardSetDma
cardSetDmaSignatureValue1 found
0200D970 : 04100010
cardSetDmaSignatureValue2 found
0200D978 : 040001A4
cardSetDmaEnd found
0200D978 : 040001A4
cardSetDmaSignatureStart used: cardSetDma not found

findCardReadDmaEndOffset:
Card read DMA end found: 0200DBA0

findCardReadDmaStartOffset:
Card read DMA start found

cardReadDma location : 0200DA4C

findCardEndReadDma

offsetDmaHandler found
0200DBAC : 02308DBC
cardEndReadDma not found

findRandomPatchOffset:
Random patch found: 0200B9C0

findMpuStartOffset:
Mpu init found: 02004A9C

findMpuDataOffset:
Mpu data found: 02004B34

findMpuInitCacheOffset:
Mpu init cache found: 02004AF4

patchMpuSize: 00000000

findMpuStartOffset:
Mpu init found: 02004AAC

findMpuDataOffset:
Mpu data found: 02004B3C

Mpu2 init: 02009378

findResetOffset
Reset not found

ERR_NONE

findSleepPatchOffset:
Sleep patch found: 02386260

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 023801B0
Relocation dst: 037F8000

Arm7 (patch v1)
[Error!] Card read addr not found

Arm7 (patch v2)
[Error!] Card read addr not found

Arm7 (patch vAll)

JumpTableFunc: 023842AC
Eeprom read:	023842B8
Eeprom page write:	023842D0
Eeprom page prog:	023842E8
Eeprom verify:	02384300
Eeprom page erase:	02384314
findSwiHaltOffset:
swiHalt call not found

swiHalt location : 00000000

findSwi12Offset:
swi 0x12 call found

findSwiGetPitchTableOffset:
swiGetPitchTable SDK <= 2 call not found
swiGetPitchTable SDK <= 2 call alt 1 not found
swiGetPitchTable SDK <= 2 call alt 2 not found
swiGetPitchTable SDK <= 2 call alt 3 not found
swiGetPitchTable SDK <= 2 call alt 4 not found
swiGetPitchTable SDK <= 2 call alt 5 not found
swiGetPitchTable SDK <= 2 call alt 6 not found
swiGetPitchTable SDK <= 2 call alt 7 not found
swiGetPitchTable SDK <= 2 call alt 8 not found
swiGetPitchTable SDK <= 2 call alt 9 not found
swiGetPitchTable SDK 3 call not found
swiGetPitchTable SDK 3 call alt 1 not found
swiGetPitchTable SDK 3 call alt 2 not found
swiGetPitchTable SDK 3 call alt 3 not found
swiGetPitchTable SDK 3 call alt 4 not found
swiGetPitchTable SDK 3 call alt 5 not found
swiGetPitchTable SDK 3 call alt 6 not found
swiGetPitchTable SDK 3 call alt 7 not found
swiGetPitchTable SDK 3 call alt 8 not found
swiGetPitchTable SDK 3 call alt 9 not found
swiGetPitchTable SDK 3 call alt 10 not found
swiGetPitchTable SDK 3 call alt 11 not found
swiGetPitchTable SDK 4 call not found
swiGetPitchTable SDK 4 call alt 1 not found
swiGetPitchTable SDK 4 call alt 2 not found
swiGetPitchTable SDK 4 call alt 3 not found
swiGetPitchTable SDK 4 call alt 4 not found
swiGetPitchTable SDK 4 call alt 5 not found
swiGetPitchTable SDK 4 call alt 6 not found
swiGetPitchTable SDK 4 call alt 7 not found
swiGetPitchTable SDK 4 call alt 8 not found
swiGetPitchTable SDK 4 call alt 9 not found

swi12 location : 02384A54

swiGetPitchTable location : 00000000

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 02389A30

ERR_NONE
handlerStartSig
020212A0
handlerEndSig
020212E0
tableAddr
027E0000
returnAddr
01FF8058
hookLocation arm9: 027E0000

ROM loaded into RAM

chipID: 0000FFC2```

### Other notes

**Comment by DraconicNEO** [comment] 2021-07-14 18:28
This doesn't work for me either.

**Comment by SoulBlast35** [comment] 2021-07-14 22:42
Considering Wii connectivity exists at all on nds-bootstrap, its impressive it gets this far. Granted, I am using USB Loader GX to run PBR, but an OG R4 running WoodR4 can connect to it without a hitch, so I highly doubt its that.

**Comment by Blood-PawWerewolf** [comment] 2021-07-15 01:00
> 
> 
> Considering Wii connectivity exists at all on nds-bootstrap, its impressive it gets this far. Granted, I am using USB Loader GX to run PBR, but an OG R4 running WoodR4 can connect to it without a hitch, so I highly doubt its that.

and im using my Wii U by using a custom made Wii VC package

**Comment by Kalanyr** [comment] 2021-07-17 02:53
This is  a dupe of https://github.com/DS-Homebrew/nds-bootstrap/issues/415 for the record.

**Comment by Kaisaan** [comment] 2021-07-17 03:12
As @Kalanyr this is just a duplicate of #415 so please move discussion there. Closing.

**Closed by Kaisaan** 2021-07-17 03:12 UTC
